defmodule Letflow.EventStore.SchemasTest do
  @moduledoc """
  Pure, no-I/O tests for REQ-023's six `Ecto.Schema` modules under
  `lib/letflow/event_store/`. See `test/specs/REQ-023.md` for the full test-case
  rationale, including the WF-02 Step 3 scope-test verdict and why the three
  moduledoc-text assertions in this file are the *weaker* half of a pair wherever a
  structural fact exists to assert instead.

  `async: true` is safe here: this module performs no database I/O at all (it reads
  only compiled module metadata via `__info__/1`, `__schema__/1` and
  `Code.fetch_docs/1`) and attaches no global `:telemetry` handler -- deliberately not
  repeating the `async: true` + global-handler mistake `docs/issues/ISS-0011.yaml`
  records. It therefore does not use `Letflow.DataCase`; there is no connection to
  check out. The database-touching half of REQ-023's coverage lives in
  `test/letflow/event_store/migrations_test.exs`, which is `async: false`.

  Moduledoc assertions read the compiled `Docs` chunk through `Code.fetch_docs/1`
  rather than reading the `.ex` file as a string, so they assert on what the module
  actually publishes (a matching sentence in an ordinary `#` comment elsewhere in the
  file would not satisfy them). Whitespace is normalised before matching so re-wrapping
  a paragraph is not a failure while deleting or weakening a claim is.
  """

  use ExUnit.Case, async: true

  alias Letflow.EventStore.ArchivedEvent
  alias Letflow.EventStore.Event
  alias Letflow.EventStore.IdempotencyRecord
  alias Letflow.EventStore.InstanceProjection
  alias Letflow.EventStore.InstanceSequence
  alias Letflow.EventStore.StoredPayload

  # A fixed literal, never DateTime.utc_now/0 -- no test in this project may depend on
  # wall-clock time (docs/guides/test_developer_guide.md principle 3).
  @fixed_created_at ~U[2026-01-02 03:04:05.000000Z]

  # ---------------------------------------------------------------------------------
  # Helpers
  # ---------------------------------------------------------------------------------

  # A schema module's own public API, with the functions `use Ecto.Schema` generates
  # (__schema__/1,2, __struct__/0,1, __changeset__/0) filtered out. Every one of those
  # is `__`-prefixed, so the filter is exact rather than a hand-maintained deny-list.
  defp own_public_api(module) do
    module.__info__(:functions)
    |> Enum.reject(fn {name, _arity} ->
      name |> Atom.to_string() |> String.starts_with?("__")
    end)
    |> Enum.sort()
  end

  # The module's published moduledoc with runs of whitespace collapsed to single
  # spaces, so an assertion on a sentence that happens to be line-wrapped in the source
  # still matches. Deliberately pattern-matches the "documented" shape: a module whose
  # moduledoc was deleted (`:none`) or hidden (`:hidden`) raises here, which is the
  # correct outcome for acceptance criteria 3, 4 and 5.
  defp normalized_moduledoc(module) do
    {:docs_v1, _anno, _lang, _format, %{"en" => moduledoc}, _meta, _docs} =
      Code.fetch_docs(module)

    String.replace(moduledoc, ~r/\s+/, " ")
  end

  # Minimal local helper mirroring the one already in test/letflow/identity_test.exs and
  # test/letflow/tenant_provisioning_test.exs.
  defp errors_on(changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {msg, opts} ->
      Regex.replace(~r"%{(\w+)}", msg, fn _, key ->
        opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
      end)
    end)
  end

  defp valid_event_attrs do
    %{
      event_id: Ecto.UUID.generate(),
      created_at: @fixed_created_at,
      instance_id: Ecto.UUID.generate(),
      event_type: "instance.started",
      payload: %{"hello" => "world"},
      actor_id: Ecto.UUID.generate(),
      sequence_number: 1,
      idempotency_key: "idem-#{System.unique_integer([:positive, :monotonic])}"
    }
  end

  # ---------------------------------------------------------------------------------
  # Acceptance criterion 2 (schema-module half): "events' migration defines the primary
  # key as (event_id, created_at), not a bare event_id, per 0003 Decision C point 2(a)"
  #
  # The migration/database half is in migrations_test.exs. Both halves exist because a
  # correct migration and an incorrect schema module (or vice versa) is a real, silent
  # failure mode.
  # ---------------------------------------------------------------------------------

  describe "acceptance criterion 2 -- composite primary key at the schema-module layer" do
    test "Event's primary key is the composite (event_id, created_at), not a bare event_id" do
      assert Event.__schema__(:primary_key) == [:event_id, :created_at]
      refute Event.__schema__(:primary_key) == [:event_id]
    end

    test "neither primary-key component is autogenerated (design INV-EV-5)" do
      # REQ-025 must mint one event_id and one created_at and bind the SAME values into
      # events, event_idempotency and (for large payloads) event_payload_store. An
      # `autogenerate` on either component would mint a second, different value at
      # insert time and silently orphan the sidecar rows -- the exact bug R-Co shipped
      # and then fixed (src/event_store/store.zig:623-636).
      assert Event.__schema__(:autogenerate) == []
      assert Event.__schema__(:autogenerate_id) == nil
    end

    test "events_archive carries the same composite primary key -- an archived event is the same row" do
      assert ArchivedEvent.__schema__(:primary_key) == [:event_id, :created_at]
    end

    test "global_seq is database-assigned (read_after_writes) and not castable by insert_changeset/2" do
      # Design INV-EV-11: the bigserial sequence assigns it, never a changeset.
      assert Event.__schema__(:read_after_writes) == [:global_seq]

      changeset = Event.insert_changeset(%Event{}, Map.put(valid_event_attrs(), :global_seq, 99))

      assert changeset.valid?
      refute Map.has_key?(changeset.changes, :global_seq)
    end
  end

  # ---------------------------------------------------------------------------------
  # Acceptance criterion 3: "the events Ecto.Schema module has no update_changeset/2 or
  # any function that issues an UPDATE against a committed row; the moduledoc states
  # this is a deliberate immutability invariant per 0003 Decision C point 1"
  #
  # The structural assertion below is an exact-set equality, not a deny-list of the two
  # names the criterion happens to mention -- the criterion's "or any function that
  # issues an UPDATE" clause is only covered by an exact set.
  # ---------------------------------------------------------------------------------

  describe "acceptance criterion 3 -- events exposes no UPDATE path (structural)" do
    test "Event's own public API is exactly insert_changeset/2 -- no update_changeset/2, no generic changeset/2, no other update path" do
      assert own_public_api(Event) == [insert_changeset: 2]

      # Stated explicitly as well as implied by the equality above, so a failure reads
      # against the criterion's own wording.
      refute Keyword.has_key?(Event.__info__(:functions), :update_changeset)
      refute Keyword.has_key?(Event.__info__(:functions), :changeset)
    end

    test "the four other append-only event-store schemas likewise expose only insert_changeset/2" do
      # events_archive holds the same immutable fact (ArchivedEvent's moduledoc);
      # instance_sequence must be incremented under a row lock rather than by a
      # read-modify-write changeset (design INV-EV-4); a stored payload belongs to an
      # immutable event; a claimed idempotency key is never re-pointed.
      for module <- [ArchivedEvent, InstanceSequence, StoredPayload, IdempotencyRecord] do
        assert own_public_api(module) == [insert_changeset: 2],
               "#{inspect(module)} exposes #{inspect(own_public_api(module))}, expected only [insert_changeset: 2]"
      end
    end

    test "InstanceProjection deliberately DOES expose update_changeset/2 -- the contrast that proves the two tests above discriminate" do
      # Without this negative control, the two assertions above would pass just as
      # happily against a directory where nobody writes changesets at all.
      # instance_projections is derived state (0003 Decision C point 3, design
      # INV-EV-9) and legitimately carries an update path.
      assert own_public_api(InstanceProjection) == [
               insert_changeset: 2,
               terminal?: 1,
               update_changeset: 2
             ]
    end
  end

  describe "acceptance criterion 3 -- events' moduledoc states the immutability invariant" do
    test "Event's moduledoc states the append-only immutability invariant and cites 0003 Decision C point 1" do
      doc = normalized_moduledoc(Event)

      assert doc =~ "This schema is append-only."

      assert doc =~
               "It deliberately exposes no `update_changeset/2`, no generic `changeset/2`, and no other function that can issue an UPDATE against a committed `events` row"

      assert doc =~ "this is a deliberate immutability invariant"
      assert doc =~ "Decision C point 1"
      assert doc =~ "Adding an update path here is a defect, not an enhancement."
    end

    test "Event's moduledoc also states the composite-primary-key rationale (acceptance criterion 2's doc side)" do
      doc = normalized_moduledoc(Event)

      assert doc =~ "The primary key is `(event_id, created_at)`, not a bare `event_id`"
    end
  end

  # ---------------------------------------------------------------------------------
  # Acceptance criterion 4: "the idempotency sidecar table has a unique index on
  # idempotency_key and its own moduledoc states it supersedes event_store.md's Open
  # Question #1 two-phase-check recommendation per 0003's resolution"
  #
  # The real database index, and the structural fact that events/events_archive carry
  # no competing index, are asserted in migrations_test.exs.
  # ---------------------------------------------------------------------------------

  describe "acceptance criterion 4 -- the idempotency sidecar" do
    test "IdempotencyRecord's moduledoc states it supersedes event_store.md's Open Question #1 two-phase check" do
      doc = normalized_moduledoc(IdempotencyRecord)

      assert doc =~ "This is the dedicated idempotency sidecar table"

      assert doc =~
               "This table supersedes R-Co's `src/design/event_store.md` \"Open Question #1\" recommendation of a two-phase deduplication check"

      assert doc =~
               "the unique index `uq_event_idempotency_key` on this table is the single enforcement point"

      assert doc =~ "Decision C point 2(b)"
    end

    test "IdempotencyRecord.insert_changeset/2 declares the uq_event_idempotency_key unique constraint by name" do
      # Pins the index NAME the changeset is wired to. If the declared name and the real
      # index name ever drift apart, a duplicate insert raises Ecto.ConstraintError
      # instead of returning {:error, changeset} -- migrations_test.exs asserts that
      # end-to-end against real Postgres, this fails in milliseconds with a precise
      # message.
      changeset =
        IdempotencyRecord.insert_changeset(%IdempotencyRecord{}, %{
          idempotency_key: "idem-#{System.unique_integer([:positive, :monotonic])}",
          event_id: Ecto.UUID.generate(),
          event_created_at: @fixed_created_at
        })

      assert changeset.valid?

      assert Enum.any?(changeset.constraints, fn constraint ->
               constraint.type == :unique and
                 constraint.constraint == "uq_event_idempotency_key" and
                 constraint.field == :idempotency_key
             end),
             "expected a :unique constraint named uq_event_idempotency_key on :idempotency_key, got #{inspect(changeset.constraints)}"
    end
  end

  # ---------------------------------------------------------------------------------
  # Acceptance criterion 5: "instance_projections' moduledoc explicitly states its
  # schema is event-store scope (this requirement) while its meaningful population is
  # EE-01/S3 scope, not built here"
  #
  # This criterion is purely a moduledoc claim -- "this table's population is somebody
  # else's job" is not expressible as a column constraint, so unlike criteria 3 and 4
  # there is no stronger structural fact to prefer. The nearest structural guard is
  # migrations_test.exs's column-set equality, which fails if S3's engine-owned columns
  # ever leak into this migration and quietly falsify the claim below.
  # ---------------------------------------------------------------------------------

  describe "acceptance criterion 5 -- instance_projections' scope statement" do
    test "InstanceProjection's moduledoc scopes the schema to the event store and its population to EE-01/S3" do
      doc = normalized_moduledoc(InstanceProjection)

      # REQ-043 note: this moduledoc's scope paragraph was deliberately reworded
      # (design req043-instance-engine-schema.md §2.3 point 1) once REQ-043
      # actually added the seven engine-owned columns REQ-023's own header
      # named as "deliberately not created here" -- the assertions below match
      # the current, accurate wording rather than the pre-REQ-043 phrasing this
      # test originally pinned.
      assert doc =~ "This table's *schema* is event-store scope"
      assert doc =~ "*meaningful population at instance start* is still EE-01 / S3 territory"
      assert doc =~ "Do not read this as the instance-engine's write logic landing early"
    end

    test "terminal?/1 is true for :completed and :cancelled only -- :error is NOT terminal" do
      # Design INV-EV-10 / event_store.md:292 (Key invariant 10) name exactly CANCELLED
      # and COMPLETED. Treating :error as terminal would silently block appends to
      # recoverable instances in REQ-025.
      #
      # The status set is read from the schema rather than hand-listed, so a future
      # fifth status fails this test until someone decides deliberately whether it is
      # terminal.
      statuses = Ecto.Enum.values(InstanceProjection, :status)

      assert Enum.sort(statuses) == [:active, :cancelled, :completed, :error]

      for status <- statuses do
        assert InstanceProjection.terminal?(status) == status in [:completed, :cancelled],
               "terminal?(#{inspect(status)}) disagrees with event_store.md Key invariant 10"
      end
    end
  end

  # ---------------------------------------------------------------------------------
  # Supporting coverage: table mapping and changeset validations. Not acceptance
  # criteria in their own right, but they pin the design's §5.1 module-to-table mapping
  # and the validations §5.1 specifies, so a silent drift in either is caught here
  # rather than at REQ-025's first integration test.
  # ---------------------------------------------------------------------------------

  describe "module-to-table mapping (design §5.1)" do
    test "each event-store schema module points at its designed table name" do
      assert Event.__schema__(:source) == "events"
      assert ArchivedEvent.__schema__(:source) == "events_archive"
      assert InstanceSequence.__schema__(:source) == "instance_sequence"
      assert InstanceProjection.__schema__(:source) == "instance_projections"
      assert StoredPayload.__schema__(:source) == "event_payload_store"
      assert IdempotencyRecord.__schema__(:source) == "event_idempotency"
    end

    test "no event-store schema module pins a compile-time @schema_prefix (design INV-EV-8)" do
      # These tables live in MANY Postgres schemas, one per tenant, so a compile-time
      # prefix would be wrong by construction -- every read and write must pass
      # `prefix: schema_name` explicitly at call time.
      for module <- [
            Event,
            ArchivedEvent,
            InstanceSequence,
            InstanceProjection,
            StoredPayload,
            IdempotencyRecord
          ] do
        assert module.__schema__(:prefix) == nil,
               "#{inspect(module)} pins @schema_prefix #{inspect(module.__schema__(:prefix))}, which INV-EV-8 forbids"
      end
    end
  end

  describe "changeset validations (pure, no I/O)" do
    test "Event.insert_changeset/2 requires every field an append must supply" do
      changeset = Event.insert_changeset(%Event{}, %{})

      refute changeset.valid?

      errors = errors_on(changeset)

      for field <- [
            :event_id,
            :created_at,
            :instance_id,
            :event_type,
            :payload,
            :actor_id,
            :sequence_number,
            :idempotency_key
          ] do
        assert Map.has_key?(errors, field),
               "expected #{field} to be required, errors: #{inspect(errors)}"
      end
    end

    test "Event.insert_changeset/2 accepts a well-formed append" do
      assert Event.insert_changeset(%Event{}, valid_event_attrs()).valid?
    end

    test "Event.insert_changeset/2 rejects an empty event_type and an over-long idempotency_key" do
      empty_type = Event.insert_changeset(%Event{}, %{valid_event_attrs() | event_type: ""})
      refute empty_type.valid?
      assert %{event_type: [_ | _]} = errors_on(empty_type)

      long_key =
        Event.insert_changeset(%Event{}, %{
          valid_event_attrs()
          | idempotency_key: String.duplicate("k", 256)
        })

      refute long_key.valid?
      assert %{idempotency_key: [_ | _]} = errors_on(long_key)
    end

    test "Event.insert_changeset/2 declares the uq_event_sequence unique constraint (ES-02, design INV-EV-4)" do
      changeset = Event.insert_changeset(%Event{}, valid_event_attrs())

      assert Enum.any?(changeset.constraints, fn constraint ->
               constraint.type == :unique and constraint.constraint == "uq_event_sequence"
             end),
             "expected a :unique constraint named uq_event_sequence, got #{inspect(changeset.constraints)}"
    end

    test "ArchivedEvent.insert_changeset/2 DOES cast global_seq -- it is copied from the source row, not allocated" do
      attrs =
        valid_event_attrs()
        |> Map.put(:global_seq, 42)
        |> Map.put(:archived_at, @fixed_created_at)

      changeset = ArchivedEvent.insert_changeset(%ArchivedEvent{}, attrs)

      assert changeset.valid?
      assert changeset.changes.global_seq == 42

      # ...and it is required, so an archive insert that forgot to copy it fails loudly.
      without_global_seq =
        ArchivedEvent.insert_changeset(%ArchivedEvent{}, Map.delete(attrs, :global_seq))

      refute without_global_seq.valid?
      assert %{global_seq: [_ | _]} = errors_on(without_global_seq)
    end

    test "InstanceSequence.insert_changeset/2 rejects a non-positive next_seq" do
      changeset =
        InstanceSequence.insert_changeset(%InstanceSequence{}, %{
          instance_id: Ecto.UUID.generate(),
          next_seq: 0
        })

      refute changeset.valid?
      assert %{next_seq: [_ | _]} = errors_on(changeset)
    end

    test "StoredPayload.insert_changeset/2 requires all four fields and rejects a non-positive byte_size" do
      empty = StoredPayload.insert_changeset(%StoredPayload{}, %{})
      refute empty.valid?

      assert %{event_id: [_ | _], event_created_at: [_ | _], payload: [_ | _], byte_size: [_ | _]} =
               errors_on(empty)

      zero_bytes =
        StoredPayload.insert_changeset(%StoredPayload{}, %{
          event_id: Ecto.UUID.generate(),
          event_created_at: @fixed_created_at,
          payload: %{"big" => "value"},
          byte_size: 0
        })

      refute zero_bytes.valid?
      assert %{byte_size: [_ | _]} = errors_on(zero_bytes)
    end

    test "InstanceProjection.update_changeset/2 structurally cannot re-point a projection at another instance" do
      projection = %InstanceProjection{
        instance_id: Ecto.UUID.generate()
      }

      changeset =
        InstanceProjection.update_changeset(projection, %{
          instance_id: Ecto.UUID.generate(),
          status: :completed,
          last_event_seq: 7
        })

      assert changeset.valid?
      refute Map.has_key?(changeset.changes, :instance_id)
      assert changeset.changes.status == :completed
      assert changeset.changes.last_event_seq == 7
    end

    test "InstanceProjection.update_changeset/2 rejects a negative last_event_seq" do
      changeset =
        InstanceProjection.update_changeset(%InstanceProjection{}, %{
          status: :active,
          last_event_seq: -1
        })

      refute changeset.valid?
      assert %{last_event_seq: [_ | _]} = errors_on(changeset)
    end
  end
end
