defmodule Letflow.Engine.SchemasTest do
  @moduledoc """
  Pure, no-I/O tests for REQ-043's two new `Ecto.Schema` modules under
  `lib/letflow/engine/` (`Letflow.Engine.Token`, `Letflow.Engine.Task`). See
  `test/specs/REQ-043.md` for the full test-case rationale, including the
  WF-02 Step 3 scope-test verdict. Mirrors the existing
  `test/letflow/event_store/schemas_test.exs` pure/integration split
  (`test/letflow/engine/migrations_test.exs` is this file's integration
  counterpart).

  `async: true` is safe here: this module performs no database I/O at all (it
  reads only compiled module metadata via `__schema__/1`, `Ecto.Enum.*` and
  `Code.fetch_docs/1`) and attaches no global `:telemetry` handler --
  deliberately not repeating the `async: true` + global-handler mistake
  `docs/issues/ISS-0011.yaml` records.
  """

  use ExUnit.Case, async: true

  alias Letflow.Engine.Task
  alias Letflow.Engine.TokenRecord, as: Token

  # ---------------------------------------------------------------------------------
  # Helpers
  # ---------------------------------------------------------------------------------

  defp errors_on(changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {msg, opts} ->
      Regex.replace(~r"%{(\w+)}", msg, fn _, key ->
        opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
      end)
    end)
  end

  # Mirrors schemas_test.exs's normalized_moduledoc/1 exactly -- reads the
  # compiled Docs chunk (never the .ex source as a string) and collapses
  # whitespace, so re-wrapping a paragraph is not a failure while deleting or
  # weakening a claim is.
  defp normalized_moduledoc(module) do
    {:docs_v1, _anno, _lang, _format, %{"en" => moduledoc}, _meta, _docs} =
      Code.fetch_docs(module)

    String.replace(moduledoc, ~r/\s+/, " ")
  end

  defp valid_token_attrs do
    %{
      instance_id: Ecto.UUID.generate(),
      node_id: "node-1",
      branch_id: "branch-1"
    }
  end

  defp valid_task_attrs do
    %{
      instance_id: Ecto.UUID.generate(),
      token_id: Ecto.UUID.generate(),
      node_id: "node-1",
      node_name: "Approve request"
    }
  end

  # ---------------------------------------------------------------------------------
  # Table/prefix mapping -- design §3.2/§4.4 ("no @schema_prefix"), §5.1/§4.1
  # (table name)
  # ---------------------------------------------------------------------------------

  describe "table mapping and multi-tenancy shape" do
    test "Token points at the tokens table and pins no compile-time @schema_prefix" do
      assert Token.__schema__(:source) == "tokens"
      assert Token.__schema__(:prefix) == nil
    end

    test "Task points at the tasks table and pins no compile-time @schema_prefix" do
      assert Task.__schema__(:source) == "tasks"
      assert Task.__schema__(:prefix) == nil
    end

    test "both primary keys are client-side autogenerated binary_ids, matching ProcessDefinition's own convention (design §4.4/§5.2)" do
      assert Token.__schema__(:primary_key) == [:id]
      assert Task.__schema__(:primary_key) == [:id]
      assert Token.__schema__(:autogenerate_id) == {:id, :id, :binary_id}
      assert Task.__schema__(:autogenerate_id) == {:id, :id, :binary_id}
    end
  end

  # ---------------------------------------------------------------------------------
  # Acceptance criterion: "a test confirming tasks.status Ecto.Enum accepts only
  # PENDING/COMPLETED/CANCELLED" -- plus the paired, deliberately-NOT-harmonized
  # casing claim (design INV-EE43-4) for tokens.status, since a test that only
  # checked one of the two tables could not tell a genuine harmonization "fix"
  # apart from the design's own deliberate asymmetry.
  # ---------------------------------------------------------------------------------

  describe "tasks.status is restricted to PENDING/COMPLETED/CANCELLED (INV-EE43-4)" do
    test "the closed value set is exactly [:pending, :completed, :cancelled]" do
      assert Enum.sort(Ecto.Enum.values(Task, :status)) == [:cancelled, :completed, :pending]
    end

    test "the dump mapping is uppercase, matching R-Co's own stored strings exactly" do
      assert Ecto.Enum.mappings(Task, :status) == [
               pending: "PENDING",
               completed: "COMPLETED",
               cancelled: "CANCELLED"
             ]
    end

    test "a status atom outside the closed set is rejected by cast, not silently coerced" do
      changeset =
        %Task{} |> Task.insert_changeset(Map.put(valid_task_attrs(), :status, :bogus))

      # :status is not even in insert_changeset/2's cast list (design §4.4 -- it is
      # completion-time-only), so a caller-supplied :status is simply ignored here
      # rather than erroring -- asserted explicitly so this test fails loudly if
      # :status is ever added to that cast list without updating this assumption.
      refute Map.has_key?(changeset.changes, :status)

      # complete_changeset/2 DOES cast :status -- this is where the enum
      # restriction is actually reachable and must reject an unknown atom.
      complete_changeset =
        Task.complete_changeset(%Task{}, %{status: :bogus})

      refute complete_changeset.valid?
      assert %{status: [_ | _]} = errors_on(complete_changeset)
    end

    test "each of the three legal status atoms is accepted by complete_changeset/2" do
      for status <- [:pending, :completed, :cancelled] do
        changeset = Task.complete_changeset(%Task{}, %{status: status})

        assert changeset.valid?,
               "#{inspect(status)} was rejected: #{inspect(errors_on(changeset))}"

        # get_field/2, not changes.status directly: casting :pending against a
        # %Task{} whose own default status is already :pending produces no
        # recorded *change* (Ecto only diffs against the base struct), so
        # changes.status would raise a KeyError for that one value in the loop
        # even though the cast legitimately succeeded.
        assert Ecto.Changeset.get_field(changeset, :status) == status
      end
    end

    test "status defaults to :pending when omitted" do
      assert %Task{}.status == :pending
    end
  end

  describe "tokens.status dumps lowercase, NOT harmonized with tasks.status (INV-EE43-4)" do
    test "the closed value set is exactly [:active, :waiting, :completed, :cancelled]" do
      assert Enum.sort(Ecto.Enum.values(Token, :status)) == [
               :active,
               :cancelled,
               :completed,
               :waiting
             ]
    end

    test "the dump mapping is lowercase -- the opposite convention from Task.status" do
      assert Ecto.Enum.mappings(Token, :status) == [
               active: "active",
               waiting: "waiting",
               completed: "completed",
               cancelled: "cancelled"
             ]
    end

    test "status defaults to :active when omitted" do
      assert %Token{}.status == :active
    end

    test "insert_changeset/2 DOES cast :status (unlike Task's), and rejects an unknown atom" do
      valid = Token.insert_changeset(%Token{}, Map.put(valid_token_attrs(), :status, :waiting))
      assert valid.valid?
      assert valid.changes.status == :waiting

      invalid = Token.insert_changeset(%Token{}, Map.put(valid_token_attrs(), :status, :bogus))
      refute invalid.valid?
      assert %{status: [_ | _]} = errors_on(invalid)
    end
  end

  # ---------------------------------------------------------------------------------
  # Changeset structure -- required fields, immutability of identity/lineage
  # fields on the "advance"/"complete" changesets (design §4.4, §5.2).
  # ---------------------------------------------------------------------------------

  describe "Token.insert_changeset/2" do
    test "requires instance_id, node_id" do
      changeset = Token.insert_changeset(%Token{}, %{})
      refute changeset.valid?
      errors = errors_on(changeset)

      for field <- [:instance_id, :node_id] do
        assert Map.has_key?(errors, field), "expected #{field} to be required"
      end
    end

    # ISS-0408 fix -- branch_id is NOT required (relaxed from the original
    # REQ-043 changeset by priv/repo/migrations/20260902000001_make_tokens_branch_id_nullable.exs):
    # Letflow.Engine.Token.branch_id's own pure type has always been
    # String.t() | nil (REQ-044 §3), and REQ-051's fire_join/5 deliberately
    # produces branch_id: nil for a PARALLEL_GATEWAY join-merged token -- a
    # real, on-record case this schema must accept, not an omission.
    test "accepts a well-formed create with a nil branch_id (join-merged token, REQ-051)" do
      attrs = Map.put(valid_token_attrs(), :branch_id, nil)
      changeset = Token.insert_changeset(%Token{}, attrs)
      assert changeset.valid?
      refute Map.has_key?(errors_on(changeset), :branch_id)
    end

    test "accepts a well-formed create" do
      assert Token.insert_changeset(%Token{}, valid_token_attrs()).valid?
    end
  end

  describe "Token.advance_changeset/2 cannot re-point identity fields (design §5.2)" do
    test "instance_id, branch_id, parent_token_id, gateway_id are structurally not castable" do
      token = %Token{
        instance_id: Ecto.UUID.generate(),
        branch_id: "branch-1",
        parent_token_id: nil,
        gateway_id: nil
      }

      changeset =
        Token.advance_changeset(token, %{
          instance_id: Ecto.UUID.generate(),
          branch_id: "branch-2",
          parent_token_id: Ecto.UUID.generate(),
          gateway_id: "gw-1",
          node_id: "node-2",
          status: :completed
        })

      assert changeset.valid?
      refute Map.has_key?(changeset.changes, :instance_id)
      refute Map.has_key?(changeset.changes, :branch_id)
      refute Map.has_key?(changeset.changes, :parent_token_id)
      refute Map.has_key?(changeset.changes, :gateway_id)

      # ...while the fields advance_changeset/2 DOES own really do change, so
      # this isn't a changeset that silently drops everything.
      assert changeset.changes.node_id == "node-2"
      assert changeset.changes.status == :completed
    end

    test "requires node_id and status" do
      # %Token{} alone has :status default to :active from the schema itself,
      # so validate_required/2 would see it as already-present regardless of
      # attrs -- a %Token{status: nil} base struct is what actually exercises
      # the required check on :status (node_id has no schema-level default, so
      # %Token{} alone is sufficient for that half).
      changeset = Token.advance_changeset(%Token{status: nil}, %{})
      refute changeset.valid?
      errors = errors_on(changeset)
      assert Map.has_key?(errors, :node_id)
      assert Map.has_key?(errors, :status)
    end
  end

  describe "Task.insert_changeset/2" do
    test "requires instance_id, token_id, node_id, node_name" do
      changeset = Task.insert_changeset(%Task{}, %{})
      refute changeset.valid?
      errors = errors_on(changeset)

      for field <- [:instance_id, :token_id, :node_id, :node_name] do
        assert Map.has_key?(errors, field), "expected #{field} to be required"
      end
    end

    test "accepts a well-formed create" do
      assert Task.insert_changeset(%Task{}, valid_task_attrs()).valid?
    end

    test "casts form_schema (sourced from the node definition at activation time) but not output_variables/completed_by/completed_at/cancelled_at" do
      attrs =
        valid_task_attrs()
        |> Map.put(:form_schema, %{"type" => "object"})
        |> Map.put(:output_variables, %{"x" => 1})
        |> Map.put(:completed_by, Ecto.UUID.generate())
        |> Map.put(:completed_at, DateTime.utc_now())

      changeset = Task.insert_changeset(%Task{}, attrs)
      assert changeset.valid?
      assert changeset.changes.form_schema == %{"type" => "object"}
      refute Map.has_key?(changeset.changes, :output_variables)
      refute Map.has_key?(changeset.changes, :completed_by)
      refute Map.has_key?(changeset.changes, :completed_at)
    end
  end

  describe "Task.complete_changeset/2 cannot re-point identity fields (design §4.4)" do
    test "instance_id, token_id, node_id, node_name are structurally not castable" do
      task = %Task{
        instance_id: Ecto.UUID.generate(),
        token_id: Ecto.UUID.generate(),
        node_id: "node-1",
        node_name: "Approve"
      }

      changeset =
        Task.complete_changeset(task, %{
          instance_id: Ecto.UUID.generate(),
          token_id: Ecto.UUID.generate(),
          node_id: "node-2",
          node_name: "Different",
          status: :completed,
          output_variables: %{"approved" => true}
        })

      assert changeset.valid?
      refute Map.has_key?(changeset.changes, :instance_id)
      refute Map.has_key?(changeset.changes, :token_id)
      refute Map.has_key?(changeset.changes, :node_id)
      refute Map.has_key?(changeset.changes, :node_name)

      assert changeset.changes.status == :completed
      assert changeset.changes.output_variables == %{"approved" => true}
    end

    test "requires status" do
      # %Task{status: nil}, not bare %Task{} -- Task's own schema-level default
      # (:pending) would otherwise satisfy validate_required/2 regardless of
      # attrs, the same reason Token's equivalent test above needs it.
      changeset = Task.complete_changeset(%Task{status: nil}, %{})
      refute changeset.valid?
      assert %{status: [_ | _]} = errors_on(changeset)
    end
  end

  # ---------------------------------------------------------------------------------
  # Moduledoc content -- design §4.3's "verbatim enough that ELIXIR-DEV cannot
  # omit the boundary statement" mandate for Task, and §5.3's resolution
  # statement for Token. Read via Code.fetch_docs/1 (compiled Docs chunk), never
  # the .ex source as a string, matching schemas_test.exs's own established
  # idiom -- and deliberately the WEAKER half of a pair wherever a structural
  # fact exists above to prefer (e.g. own_public_api-style checks aren't
  # meaningful here since REQ-043 intentionally ships no context-module
  # function at all, so there's nothing structural to assert beyond the
  # changeset shapes already covered above).
  # ---------------------------------------------------------------------------------

  describe "Task's moduledoc states the store.zig-not-ported boundary (design §4.3)" do
    test "cites src/tasks/store.zig and states the query/list/filter surface is not ported by this module or REQ-043" do
      doc = normalized_moduledoc(Task)

      assert doc =~ "src/tasks/store.zig"
      assert doc =~ "that surface is not ported by this module or by REQ-043 at all"

      assert doc =~
               "It belongs to S4's tasks routes or its own later requirement, per `docs/migration/stage-3-instance-engine.md`'s explicit scope boundary"

      assert doc =~
               "it is schema only, with no query/list/filter functions of its own"
    end

    test "states no context-module write path exists yet (design §4.3 point 2)" do
      doc = normalized_moduledoc(Task)

      assert doc =~ "no context-module write path"
      assert doc =~ "REQ-045/051's job"
    end

    test "states status dumps uppercase, contrasted explicitly with Token's lowercase (design §4.3 point 3)" do
      doc = normalized_moduledoc(Task)

      assert doc =~ "unlike `Letflow.Engine.TokenRecord.status`, which dumps lowercase"
    end

    test "states the tenant_id column was dropped by Decision 0006 D2 and must not be re-added" do
      doc = normalized_moduledoc(Task)

      assert doc =~ "No `tenant_id` column (Decision 0006 D2)"
      assert doc =~ "Do not re-add a `tenant_id` field to this schema"
    end
  end

  describe "Token's moduledoc states the tokens-table resolution (design §5.3)" do
    test "states the table exists for Task.token_id's FK, not because current_nodes was insufficient" do
      doc = normalized_moduledoc(Token)

      assert doc =~ "requires a real"
      assert doc =~ "FK-referenceable row"
      assert doc =~ "cannot serve as a foreign-key target"

      assert doc =~
               "not because `current_nodes` was found insufficient for split/join computation on its own terms"
    end

    test "states instance_projections.current_nodes remains the engine's authoritative summary" do
      doc = normalized_moduledoc(Token)

      assert doc =~ "remains the engine's authoritative summary of active token positions"
    end

    test "states status dumps lowercase, a fixed convention distinct from Task.status's uppercase (design §5.3 point 4)" do
      doc = normalized_moduledoc(Token)

      assert doc =~ "a fixed convention per design"
      assert doc =~ "this codebase already has a same-shaped table using the opposite casing"
    end
  end
end
