defmodule Letflow.Engine.Wasm.ModuleVersionRegistry do
  @moduledoc """
  REQ-173 (WASM-14, MUST — "When a new version of a module is activated,
  in-flight invocations of the prior version MUST complete normally. New
  invocations MUST use the new version.").

  A new, third module — `Letflow.Engine.Wasm.ModuleRegistry` (REQ-166),
  `Letflow.Engine.Wasm.CapabilityGate` (REQ-167/171/172), and
  `Letflow.Engine.Wasm.PluginHandler` (REQ-165/170/171/172) are none of them
  modified by this requirement — that *composes* the three above to add
  versioned registration, an explicit activation operation, a minimal but
  real `invoke/4` entry point that exercises the checkout → instantiate →
  call → release sequence end to end, and introspection for tests. See
  `lib/letflow/design/req173-wasm-module-hot-reload.md` (gate-approved) for
  the full design this module implements verbatim — in particular §4 (the
  concurrency mechanism), §5 (why registration validation stays out of this
  `GenServer`'s own loop), and §6 (reference counting and the release
  predicate, including the crash-safety net this module's `handle_info/2`
  `:DOWN` clause provides).

  ## The mechanism, in one paragraph (design §4)

  `invoke/4` spawns steps 1-6 as the body of one
  `Task.Supervisor.async_nolink/2` task under
  `Letflow.Engine.Wasm.ModuleVersionRegistryTaskSupervisor`, then blocks on
  `Task.yield/2` bounded by `timeout_ms + @outer_yield_margin_ms` (a strictly
  larger, internally-computed outer bound — never a second public
  parameter). Step 1, run inside that task, checks out an immutable
  `version_snapshot()` from this `GenServer`'s current state — incrementing
  that version's `ref_count` and setting a `Process.monitor/1` on the task
  itself — which is the single instant an in-flight invocation's version is
  decided; nothing after that step ever consults `current_version_id` again
  for that invocation. A concurrent `activate/2` can therefore never affect
  an invocation already past checkout: it only ever moves
  `current_version_id` and, once safe (§6's release predicate), nils out a
  *different*, already-superseded version's heavy fields — never the
  snapshot a task already holds a value copy of.

  ## Why this `GenServer`'s own loop never blocks (design §4's INV-MVR-1)

  This process never calls `Wasmex.start_link/1`, `Wasmex.call_function/4`,
  any function that runs guest code, or `ModuleRegistry.register/1`'s own
  validating call (§5 explains why registration validation is kept out too).
  Every `handle_call/3` clause is a pure, O(map-size) state transition with
  no I/O and no blocking wait — a guest parked indefinitely in a host call
  (e.g. this design's own §8 test scenario) blocks only its own dedicated
  Wasmex instance process and the one task that owns it, never this
  registry, and therefore never `activate/2` for the same or any other
  `module_name`.

  ## Crash-safety net (design §6)

  The `Process.monitor/1` set at checkout time covers BOTH ways a task can
  fail to reach step 6's explicit `release` call on its own: (1) step 4's
  `Wasmex.call_function/4` `GenServer.call` timing out at the caller-supplied
  `timeout_ms`, crashing the task with an ordinary, uncaught `exit`; and (2)
  `invoke/4`'s own outer `Task.yield/2` bound elapsing, causing
  `Task.shutdown(task, :brutal_kill)`. `:DOWN` messages are generated by the
  BEAM for *any* reason a monitored process terminates, so
  `handle_info({:DOWN, ...}, state)` performs the identical
  decrement-and-check-release-predicate logic step 6 performs explicitly,
  keyed off the same `monitor_ref`. An explicit `release` call always
  `Process.demonitor/2`s (`[:flush]`) first, so an ordinary release and the
  `:DOWN` handler are mutually exclusive for a given `monitor_ref` — `ref_count`
  can never be double-decremented.
  """

  use GenServer

  alias Letflow.Engine.Wasm.CapabilityGate
  alias Letflow.Engine.Wasm.HostApi
  alias Letflow.Engine.Wasm.ModuleRegistry

  @task_supervisor Letflow.Engine.Wasm.ModuleVersionRegistryTaskSupervisor

  # §3 — the OUTER Task.yield/2 bound is invoke/4's own timeout_ms plus this
  # fixed margin, never a second public parameter. Mirrors the real
  # asymmetry already live between PluginInterface's own outer default
  # (30_000ms) and PluginHandler's own inner default (5_000ms).
  @outer_yield_margin_ms 2_000

  # design §4 step 3 -- an ELIXIR-DEV implementation constant bounding the
  # nested instantiation-attempt task, mirroring ModuleRegistry's and
  # CapabilityGate's own identical @instantiation_timeout_ms constants.
  @instantiation_timeout_ms 5_000

  # Matches the exact wording wasmex v0.15.1 produces for an unresolved
  # import -- deliberately duplicated from ModuleRegistry/CapabilityGate's
  # own identical private classifiers (design §4 step 3, §7: "each module
  # keeps its own private crash classifier").
  @unresolved_import_pattern ~r/unknown import: `(?<namespace>[^:`]+)::(?<function>[^`]+)` has not been defined/

  @typedoc "Design §2 — admin-assigned logical identity, stable across versions."
  @type module_name :: String.t()

  @typedoc "Design §2 — assigned by this registry, 1-based, monotonically increasing per module_name."
  @type version_id :: pos_integer()

  @typedoc "Design §2."
  @type version_status ::
          :active
          | :superseded
          | :released
          | {:unknown_version, module_name()}
          | {:unknown_module, module_name()}

  @typedoc """
  Design §2 — the immutable value `checkout` hands to an invocation, copied
  by value across the `GenServer.call/3` reply boundary. Because
  Erlang/Elixir terms handed across a `GenServer.call/3` reply are copied,
  no later registry operation can mutate a snapshot already held by an
  in-flight invocation, structurally.
  """
  @type version_snapshot :: %{
          module_name: module_name(),
          version_id: version_id(),
          registered_module: ModuleRegistry.registered_module(),
          manifest: CapabilityGate.manifest()
        }

  @typedoc false
  @type version_entry :: %{
          version_id: version_id(),
          registered_module: ModuleRegistry.registered_module() | nil,
          manifest: CapabilityGate.manifest() | nil,
          ref_count: non_neg_integer(),
          monitors: %{reference() => pid()}
        }

  @typedoc false
  @type module_state :: %{
          current_version_id: version_id() | nil,
          versions: %{version_id() => version_entry()},
          next_version_seq: pos_integer()
        }

  @typedoc false
  @type registry_state :: %{optional(module_name()) => module_state()}

  # ── Public API (design §3) ──────────────────────────────────────────────

  @doc "Supervised singleton, registered as `#{inspect(__MODULE__)}`."
  @spec start_link(opts :: keyword()) :: GenServer.on_start()
  def start_link(opts \\ []) when is_list(opts) do
    name = Keyword.get(opts, :name, __MODULE__)
    GenServer.start_link(__MODULE__, opts, name: name)
  end

  @doc """
  Design §3 — stage 1/2 ABI validation (`ModuleRegistry.register/1`) runs in
  the CALLING process, never inside this registry's own `GenServer` loop
  (see §5). Only on `{:ok, registered_module}` does this function make one
  fast internal call to commit the new `version_entry()`. Does not affect
  `current_version_id` — a brand-new version stays inert until `activate/2`
  is called explicitly.
  """
  @spec register_version(module_name(), bytes :: binary(), CapabilityGate.manifest()) ::
          {:ok, version_id()} | {:error, ModuleRegistry.registration_error()}
  def register_version(module_name, bytes, %{capabilities: _} = manifest)
      when is_binary(module_name) and is_binary(bytes) do
    case ModuleRegistry.register(bytes) do
      {:ok, registered_module} ->
        GenServer.call(__MODULE__, {:commit_version, module_name, registered_module, manifest})

      {:error, _reason} = error ->
        error
    end
  end

  @doc """
  Design §3 — sets `current_version_id := version_id`. If the previous
  current version's `ref_count` is already `0` at this instant, §6's release
  predicate fires immediately, in the same call. A no-op activation
  (activating the version that is already current) is idempotent — it does
  not reset `ref_count` or touch `monitors`.
  """
  @spec activate(module_name(), version_id()) ::
          :ok
          | {:error, {:unknown_module, module_name()}}
          | {:error, {:unknown_version, module_name(), version_id()}}
  def activate(module_name, version_id)
      when is_binary(module_name) and is_integer(version_id) do
    GenServer.call(__MODULE__, {:activate, module_name, version_id})
  end

  @spec current_version(module_name()) ::
          {:ok, version_id()}
          | {:error, {:unknown_module, module_name()}}
          | {:error, {:no_active_version, module_name()}}
  def current_version(module_name) when is_binary(module_name) do
    GenServer.call(__MODULE__, {:current_version, module_name})
  end

  @doc "Test/introspection accessor (design §3)."
  @spec version_status(module_name(), version_id()) :: version_status()
  def version_status(module_name, version_id)
      when is_binary(module_name) and is_integer(version_id) do
    GenServer.call(__MODULE__, {:version_status, module_name, version_id})
  end

  @doc """
  Design §3/§4 — the minimal real invocation path this requirement needs to
  exercise and test the hot-reload property end to end. `invoke/4` itself —
  never the spawned task, never this `GenServer`'s own loop — blocks on
  `Task.yield/2`, so it is a synchronous function that never hands a `Task`
  back to its own caller.

  `timeout_ms` is the INNER bound, threaded verbatim into step 4's
  `Wasmex.call_function/4` call. The OUTER bound passed to `Task.yield/2` is
  the strictly larger, internally-computed
  `timeout_ms + #{@outer_yield_margin_ms}`.

  This mirrors, without reusing the code of,
  `Letflow.Engine.PluginInterface.invoke/2,3`'s own two-layer dispatch
  (`async_nolink -> Task.yield/2 -> Task.shutdown(:brutal_kill)`), per
  decision 0014.
  """
  @spec invoke(
          module_name(),
          export :: String.t(),
          args :: [integer()],
          execution_context :: HostApi.execution_context(),
          timeout_ms :: pos_integer()
        ) ::
          {:ok, version_id(), [integer()]}
          | {:error, {:unknown_module, module_name()}}
          | {:error, {:no_active_version, module_name()}}
          | {:error, {:instantiation_denied, CapabilityGate.instantiation_defect()}}
          | {:error, {:call_failed, term()}}
          | {:error, {:timeout, timeout_ms :: pos_integer()}}
  def invoke(module_name, export, args, execution_context, timeout_ms)
      when is_binary(module_name) and is_binary(export) and is_list(args) and
             is_integer(timeout_ms) and timeout_ms > 0 do
    task =
      Task.Supervisor.async_nolink(@task_supervisor, fn ->
        do_invoke(module_name, export, args, execution_context, timeout_ms)
      end)

    case Task.yield(task, timeout_ms + @outer_yield_margin_ms) do
      {:ok, result} ->
        result

      {:exit, {:timeout, {GenServer, :call, _}}} ->
        {:error, {:timeout, timeout_ms}}

      {:exit, reason} ->
        {:error, {:call_failed, reason}}

      nil ->
        Task.shutdown(task, :brutal_kill)
        {:error, {:timeout, timeout_ms}}
    end
  end

  # ── The task-side algorithm (design §4 steps 1-6) ───────────────────────

  @spec do_invoke(module_name(), String.t(), [integer()], HostApi.execution_context(), pos_integer()) ::
          {:ok, version_id(), [integer()]}
          | {:error, {:unknown_module, module_name()}}
          | {:error, {:no_active_version, module_name()}}
          | {:error, {:instantiation_denied, CapabilityGate.instantiation_defect()}}
          | {:error, {:call_failed, term()}}
  defp do_invoke(module_name, export, args, execution_context, timeout_ms) do
    case checkout(module_name) do
      {:error, _reason} = error ->
        error

      {:ok, snapshot, monitor_ref} ->
        table = CapabilityGate.build_import_table(snapshot.manifest, execution_context)

        case instantiate(snapshot.registered_module.bytes, table) do
          {:ok, pid} ->
            run_call(snapshot, monitor_ref, pid, export, args, timeout_ms)

          {:error, defect} ->
            release(snapshot.module_name, snapshot.version_id, monitor_ref)
            {:error, {:instantiation_denied, defect}}
        end
    end
  end

  # Step 4/5/6 -- calls the guest export, stops the instance unconditionally
  # (step 5), and releases the checkout (step 6) on every path except the
  # ONE path design §6 deliberately leaves to the Process.monitor/:DOWN
  # crash-safety net: an ordinary Elixir exception here IS caught (rescue),
  # cleaned up, and re-raised; a GenServer.call timeout `exit` from
  # Wasmex.call_function/4 itself is never intercepted by `rescue` at all
  # (Elixir's `rescue` never observes an `exit`), so it is deliberately left
  # to propagate uncaught out of this task -- exactly the path the
  # crash-safety net exists to cover (design §6 point 1).
  @spec run_call(version_snapshot(), reference(), pid(), String.t(), [integer()], pos_integer()) ::
          {:ok, version_id(), [integer()]} | {:error, {:call_failed, term()}}
  defp run_call(snapshot, monitor_ref, pid, export, args, timeout_ms) do
    call_result =
      try do
        Wasmex.call_function(pid, export, args, timeout_ms)
      rescue
        exception ->
          GenServer.stop(pid)
          release(snapshot.module_name, snapshot.version_id, monitor_ref)
          reraise exception, __STACKTRACE__
      end

    GenServer.stop(pid)
    release(snapshot.module_name, snapshot.version_id, monitor_ref)

    case call_result do
      {:ok, result} -> {:ok, snapshot.version_id, result}
      {:error, reason} -> {:error, {:call_failed, reason}}
    end
  end

  # Step 3 -- the real instantiation attempt, run inside a nested,
  # monitored Task.Supervisor.async_nolink/2 task under the same task
  # supervisor (never called inline -- the identical unresolved-import
  # crash-propagation hazard ModuleRegistry/CapabilityGate's own moduledocs
  # document).
  @spec instantiate(binary(), CapabilityGate.import_table()) ::
          {:ok, pid()} | {:error, CapabilityGate.instantiation_defect()}
  defp instantiate(bytes, table) do
    task =
      Task.Supervisor.async_nolink(@task_supervisor, fn ->
        Wasmex.start_link(%{bytes: bytes, imports: table})
      end)

    case Task.yield(task, @instantiation_timeout_ms) do
      {:ok, {:ok, pid}} ->
        {:ok, pid}

      {:ok, {:error, reason}} ->
        {:error, {:crashed, reason}}

      {:exit, reason} ->
        {:error, classify_crash(reason)}

      nil ->
        Task.shutdown(task, :brutal_kill)
        {:error, {:timeout, @instantiation_timeout_ms}}
    end
  end

  @spec classify_crash(term()) :: CapabilityGate.instantiation_defect()
  defp classify_crash({{:badmatch, {:error, message}}, _stacktrace} = reason)
       when is_binary(message) do
    case Regex.named_captures(@unresolved_import_pattern, message) do
      %{"namespace" => namespace, "function" => function} ->
        {:unresolved_import, namespace, function}

      nil ->
        {:crashed, reason}
    end
  end

  defp classify_crash(reason), do: {:crashed, reason}

  # Step 1 -- checkout, issued from the task process (`self()` there is the
  # task's own pid, which is what gets monitored).
  @spec checkout(module_name()) ::
          {:ok, version_snapshot(), reference()}
          | {:error, {:unknown_module, module_name()}}
          | {:error, {:no_active_version, module_name()}}
  defp checkout(module_name) do
    GenServer.call(__MODULE__, {:checkout, module_name})
  end

  # Step 6 -- explicit release, on every path steps 2-5 reach normally.
  @spec release(module_name(), version_id(), reference()) :: :ok
  defp release(module_name, version_id, monitor_ref) do
    GenServer.call(__MODULE__, {:release, module_name, version_id, monitor_ref})
  end

  # ── GenServer callbacks -- every clause below is a pure, O(map-size)
  # state transition with no I/O and no blocking wait (design §4's
  # INV-MVR-1). ─────────────────────────────────────────────────────────

  @impl GenServer
  def init(_opts) do
    {:ok, %{}}
  end

  @impl GenServer
  def handle_call({:commit_version, module_name, registered_module, manifest}, _from, state) do
    module_state =
      Map.get(state, module_name, %{current_version_id: nil, versions: %{}, next_version_seq: 1})

    version_id = module_state.next_version_seq

    entry = %{
      version_id: version_id,
      registered_module: registered_module,
      manifest: manifest,
      ref_count: 0,
      monitors: %{}
    }

    new_module_state = %{
      module_state
      | versions: Map.put(module_state.versions, version_id, entry),
        next_version_seq: version_id + 1
    }

    {:reply, {:ok, version_id}, Map.put(state, module_name, new_module_state)}
  end

  def handle_call({:activate, module_name, version_id}, _from, state) do
    case Map.fetch(state, module_name) do
      :error ->
        {:reply, {:error, {:unknown_module, module_name}}, state}

      {:ok, module_state} ->
        if Map.has_key?(module_state.versions, version_id) do
          previous_id = module_state.current_version_id

          new_module_state =
            %{module_state | current_version_id: version_id}
            |> maybe_release_superseded(previous_id, version_id)

          {:reply, :ok, Map.put(state, module_name, new_module_state)}
        else
          {:reply, {:error, {:unknown_version, module_name, version_id}}, state}
        end
    end
  end

  def handle_call({:current_version, module_name}, _from, state) do
    reply =
      case Map.fetch(state, module_name) do
        :error -> {:error, {:unknown_module, module_name}}
        {:ok, %{current_version_id: nil}} -> {:error, {:no_active_version, module_name}}
        {:ok, %{current_version_id: version_id}} -> {:ok, version_id}
      end

    {:reply, reply, state}
  end

  def handle_call({:version_status, module_name, version_id}, _from, state) do
    reply =
      case Map.fetch(state, module_name) do
        :error ->
          {:unknown_module, module_name}

        {:ok, module_state} ->
          case Map.fetch(module_state.versions, version_id) do
            :error -> {:unknown_version, module_name}
            {:ok, entry} -> status_for(module_state, entry)
          end
      end

    {:reply, reply, state}
  end

  def handle_call({:checkout, module_name}, {task_pid, _tag}, state) do
    case Map.fetch(state, module_name) do
      :error ->
        {:reply, {:error, {:unknown_module, module_name}}, state}

      {:ok, %{current_version_id: nil}} ->
        {:reply, {:error, {:no_active_version, module_name}}, state}

      {:ok, module_state} ->
        version_id = module_state.current_version_id
        entry = Map.fetch!(module_state.versions, version_id)

        monitor_ref = Process.monitor(task_pid)

        new_entry = %{
          entry
          | ref_count: entry.ref_count + 1,
            monitors: Map.put(entry.monitors, monitor_ref, task_pid)
        }

        new_module_state = put_entry(module_state, version_id, new_entry)

        snapshot = %{
          module_name: module_name,
          version_id: version_id,
          registered_module: new_entry.registered_module,
          manifest: new_entry.manifest
        }

        {:reply, {:ok, snapshot, monitor_ref}, Map.put(state, module_name, new_module_state)}
    end
  end

  def handle_call({:release, module_name, version_id, monitor_ref}, _from, state) do
    Process.demonitor(monitor_ref, [:flush])
    new_state = do_release(state, module_name, version_id, monitor_ref)
    {:reply, :ok, new_state}
  end

  @impl GenServer
  def handle_info({:DOWN, monitor_ref, :process, _pid, _reason}, state) do
    {:noreply, release_by_monitor_ref(state, monitor_ref)}
  end

  def handle_info(_message, state), do: {:noreply, state}

  # ── Internal state-transition helpers ───────────────────────────────────

  defp status_for(%{current_version_id: current_version_id}, entry) do
    cond do
      is_nil(entry.registered_module) -> :released
      entry.version_id == current_version_id -> :active
      true -> :superseded
    end
  end

  # No-op (idempotent) activation -- does not touch ref_count/monitors.
  defp maybe_release_superseded(module_state, previous_id, version_id)
       when is_nil(previous_id) or previous_id == version_id do
    module_state
  end

  defp maybe_release_superseded(module_state, previous_id, _version_id) do
    apply_release_predicate(module_state, previous_id)
  end

  defp do_release(state, module_name, version_id, monitor_ref) do
    case Map.fetch(state, module_name) do
      :error ->
        state

      {:ok, module_state} ->
        case Map.fetch(module_state.versions, version_id) do
          :error ->
            state

          {:ok, entry} ->
            new_entry = %{
              entry
              | ref_count: max(entry.ref_count - 1, 0),
                monitors: Map.delete(entry.monitors, monitor_ref)
            }

            new_module_state =
              module_state
              |> put_entry(version_id, new_entry)
              |> apply_release_predicate(version_id)

            Map.put(state, module_name, new_module_state)
        end
    end
  end

  defp release_by_monitor_ref(state, monitor_ref) do
    Enum.reduce(state, state, fn {module_name, module_state}, acc ->
      case find_version_by_monitor(module_state, monitor_ref) do
        nil ->
          acc

        version_id ->
          entry = Map.fetch!(module_state.versions, version_id)

          new_entry = %{
            entry
            | ref_count: max(entry.ref_count - 1, 0),
              monitors: Map.delete(entry.monitors, monitor_ref)
          }

          new_module_state =
            module_state
            |> put_entry(version_id, new_entry)
            |> apply_release_predicate(version_id)

          Map.put(acc, module_name, new_module_state)
      end
    end)
  end

  defp find_version_by_monitor(module_state, monitor_ref) do
    Enum.find_value(module_state.versions, fn {version_id, entry} ->
      if Map.has_key?(entry.monitors, monitor_ref), do: version_id
    end)
  end

  # Design §6's release predicate, checked at exactly two trigger points
  # (inside `release`/`:DOWN`, and inside `activate`) and nowhere else: a
  # version_entry's registered_module/manifest are set to nil (status
  # becomes :released) the instant it is both (a) not current_version_id
  # and (b) ref_count 0.
  defp apply_release_predicate(module_state, version_id) do
    entry = Map.fetch!(module_state.versions, version_id)

    if entry.ref_count == 0 and module_state.current_version_id != version_id and
         not is_nil(entry.registered_module) do
      put_entry(module_state, version_id, %{entry | registered_module: nil, manifest: nil})
    else
      module_state
    end
  end

  defp put_entry(module_state, version_id, entry) do
    %{module_state | versions: Map.put(module_state.versions, version_id, entry)}
  end
end
