defmodule Letflow.EventStore.Event do
  @moduledoc """
  Ecto schema for the `events` table — the append-only event log R-Co's
  `src/design/event_store.md` documents (Covers: ES-01..ES-08). See
  `lib/letflow/design/req023-event-store-schema.md` §3.1 and §5.1 for the full
  design this module implements.

  ## Immutability (REQ-023 acceptance criterion 3)

  This schema is append-only. It deliberately exposes no `update_changeset/2`,
  no generic `changeset/2`, and no other function that can issue an UPDATE
  against a committed `events` row — this is a deliberate immutability
  invariant, per `docs/migration/decisions/0003-ecto-schema-strategy.md`
  Decision C point 1 (append-only/immutability, the decision's first
  top-level numbered point) and R-Co's `src/design/event_store.md` Key
  invariant 1. Ecto's changeset-based `update/2` pattern does not
  structurally forbid an update the way a database trigger or a restricted
  grant would, so this invariant is enforced at the application/
  schema-module layer, not by the migration file — 0003 point 1 states
  exactly that. Adding an update path here is a defect, not an enhancement.

  ## Composite primary key

  The primary key is `(event_id, created_at)`, not a bare `event_id` — 0003
  Decision C point 2(a), applied from the first migration so a future
  partitioning retrofit is never also a primary-key-shape migration.

  ## `event_id`/`created_at` are NOT autogenerated (design INV-EV-5)

  PROVENANCE (historical, not current decision authority):
  Neither field carries `autogenerate`. This is deliberate and is the single
  most easily-missed detail in this design: REQ-025 must mint `event_id`
  exactly once and bind the *same* value into `events`, `event_idempotency`
  and (for large payloads) `event_payload_store`, and must bind one
  `created_at` value into all three as well. R-Co shipped and then fixed the
  exact bug this prevents — two independent `gen_random_uuid()` evaluations
  orphaning the sidecar row from the event it points at
  (`src/event_store/store.zig:623-636`) — and separately documents binding
  "the SAME created_at" across statements (`store.zig:856-864`).

  ## `global_seq` (design INV-EV-11)

  Assigned by the database's own `bigserial` sequence, never by a changeset —
  hence `read_after_writes: true` and its absence from `insert_changeset/2`'s
  cast list. It is monotone but **not gap-free**: rolled-back transactions
  consume sequence values. Consumers must treat it as a cursor, never as a
  count.

  ## No `@schema_prefix` (design INV-EV-8)

  This table lives in *many* Postgres schemas, one per tenant, so pinning a
  single prefix at compile time would be wrong. Every read and write must pass
  `prefix: schema_name` explicitly at call time, where `schema_name` comes
  from a `Letflow.TenantProvisioning.Registration` row. That is REQ-025's and
  REQ-026's responsibility; this module takes no position on which tenant a
  given query targets.

  ## Idempotency lives elsewhere (design INV-EV-3)

  `idempotency_key` is stored here but carries **no** unique index on this
  table. The ES-03 global-uniqueness invariant is enforced solely by
  `Letflow.EventStore.IdempotencyRecord`'s `uq_event_idempotency_key`.

  ## No `tenant_id` column (Decision 0006 D2)

  This table carried `tenant_id` until Decision 0006 D2
  (`docs/migration/decisions/0006-identity-tables-schema-per-tenant.md`)
  dropped it from every event-store table — the per-tenant Postgres schema
  already identifies the owning tenant, and 0006 §R3 documents that this
  table's own original migration header already conceded the column carried
  at most one distinct value per schema. See `lib/letflow/design/req023-event-store-schema.md`
  §2.5 for the superseded asymmetry rationale (retained there for history,
  not as current guidance).
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key false
  schema "events" do
    field(:event_id, Ecto.UUID, primary_key: true)
    field(:created_at, :utc_datetime_usec, primary_key: true)
    field(:instance_id, Ecto.UUID)
    field(:event_type, :string)
    field(:payload, :map)
    field(:actor_id, Ecto.UUID)
    field(:sequence_number, :integer)
    field(:idempotency_key, :string)
    field(:metadata, :map, default: %{})
    field(:global_seq, :integer, read_after_writes: true)
  end

  @type t :: %__MODULE__{}

  @cast_fields [
    :event_id,
    :created_at,
    :instance_id,
    :event_type,
    :payload,
    :actor_id,
    :sequence_number,
    :idempotency_key,
    :metadata
  ]

  @required_fields [
    :event_id,
    :created_at,
    :instance_id,
    :event_type,
    :payload,
    :actor_id,
    :sequence_number,
    :idempotency_key
  ]

  @doc """
  The only changeset this module exposes — structural validation for a single
  append. Does no I/O; the `{:ok, struct} | {:error, changeset}` boundary is
  `Repo.insert/2`'s, inside REQ-025's context module.

  `global_seq` is deliberately not castable (the database sequence assigns it),
  and there is deliberately no update counterpart — see this module's
  moduledoc.
  """
  @spec insert_changeset(t(), attrs :: map()) :: Ecto.Changeset.t()
  def insert_changeset(event, attrs) do
    event
    |> cast(attrs, @cast_fields)
    |> validate_required(@required_fields)
    |> validate_length(:idempotency_key, min: 1, max: 255)
    |> validate_length(:event_type, min: 1, max: 128)
    |> unique_constraint([:instance_id, :sequence_number], name: :uq_event_sequence)
  end
end
