defmodule Letflow.EventStore.InstanceSequence do
  @moduledoc """
  Ecto schema for the `instance_sequence` table — the per-instance sequence-lock
  row R-Co's `src/design/event_store.md` "Concurrency design" section describes.
  See `lib/letflow/design/req023-event-store-schema.md` §3.2 and §5.1.

  One row per workflow instance, holding the next `sequence_number` that
  instance's next event will take. `instance_id` is the natural primary key, and
  it is deliberately **not** autogenerated: the instance id is minted by the
  engine, never by this row.

  ## No `update_changeset/2`, deliberately (design INV-EV-4)

  The increment is performed by REQ-025 as a single atomic statement under a row
  lock (`SELECT ... FOR UPDATE`, then increment, inside the append transaction —
  `event_store.md:353-367`). A changeset-mediated read-modify-write would
  reintroduce exactly the lost-update race that protocol exists to prevent, so
  `insert_changeset/2` (first-append row creation) is the only changeset here.

  ## No `@schema_prefix` (design INV-EV-8)

  Like every event-store schema module, this table lives in many Postgres
  schemas — one per tenant — so every read and write must pass
  `prefix: schema_name` explicitly at call time rather than relying on a
  compile-time prefix.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:instance_id, :binary_id, autogenerate: false}
  schema "instance_sequence" do
    field(:next_seq, :integer, default: 1)
  end

  @type t :: %__MODULE__{}

  @doc """
  Structural changeset for creating an instance's sequence row on its first
  append. Does no I/O. There is deliberately no update counterpart — see this
  module's moduledoc.
  """
  @spec insert_changeset(t(), attrs :: map()) :: Ecto.Changeset.t()
  def insert_changeset(instance_sequence, attrs) do
    instance_sequence
    |> cast(attrs, [:instance_id, :next_seq])
    |> validate_required([:instance_id])
    |> validate_number(:next_seq, greater_than: 0)
  end
end
