defmodule Letflow.Audit.ChainLock do
  @moduledoc """
  Ecto schema for the `audit_chain_locks` table (ISS-0979) -- the per-tenant
  sentinel row `Letflow.Audit.insert_entry/3` locks (`SELECT ... FOR UPDATE`)
  before reading `audit_entries`' chain tail, so two concurrent writers for
  the same tenant can never both observe the same tail and fork the chain.
  See `lib/letflow/design/iss0979-audit-chain-lock.md` section 3.2 for the
  full design this module implements.

  One row per tenant, holding no data of its own -- `tenant_id` is the
  natural primary key, and it is deliberately **not** autogenerated: the
  tenant id already exists (minted by `Letflow.Identity.Tenant`) by the time
  this row is ever inserted.

  ## No `update_changeset/2`, deliberately

  Same reasoning as `Letflow.EventStore.InstanceSequence`'s own moduledoc:
  this row is never updated, only inserted-if-absent and locked. A changeset-
  mediated update path would invite exactly the kind of accidental
  read-modify-write this table exists to avoid. `insert_changeset/2`
  (first-write row creation) is the only changeset here.

  ## No `@schema_prefix`

  Like every other tenant-scoped schema module, this table lives in many
  Postgres schemas -- one per tenant -- so every read and write must pass
  `prefix: schema_name` explicitly at call time rather than relying on a
  compile-time prefix.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:tenant_id, :binary_id, autogenerate: false}
  schema "audit_chain_locks" do
  end

  @type t :: %__MODULE__{}

  @doc """
  Structural changeset for creating a tenant's chain-lock row on its first
  `insert_entry/3` call. Does no I/O. There is deliberately no update
  counterpart -- see this module's moduledoc.
  """
  @spec insert_changeset(t(), %{tenant_id: Ecto.UUID.t()}) :: Ecto.Changeset.t()
  def insert_changeset(chain_lock, attrs) do
    chain_lock
    |> cast(attrs, [:tenant_id])
    |> validate_required([:tenant_id])
  end
end
