/* @generated by tools/codegen_list_page.py — boilerplate is auto-generated.
   Edit only inside CUSTOM blocks. Re-run codegen to refresh. */
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { servicesApi, type RegisterServiceBody, type ServiceRecord } from '@/api/services'
import { queryKeys } from '@/api/queryKeys'
import { useAuth } from '@/auth/AuthContext'
import { QueryStateBoundary } from '@/components/ui/QueryStateBoundary'
import { classifyError, type RendererState } from '@/utils/classifyError'

/**
 * ServicesPage — SVC-04
 * Platform-admins: full list via /api/v1/admin/services, owner_tenant column, Register button.
 * Other authenticated users: tenant-scoped list via /api/v1/services, read-only.
 */
export default function ServicesPage() {
  const queryClient = useQueryClient()
  const { session } = useAuth()

  {/* CUSTOM: role-gate */}
  const isPlatformAdmin = Boolean(session?.roles.includes('PLATFORM_ADMIN'))

  const [search, setSearch] = useState('')
  const [scope, setScope] = useState('')
  const [showCreate, setShowCreate] = useState(false)
  const [editTarget, setEditTarget] = useState<ServiceRecord | null>(null)
  const [editScope, setEditScope] = useState<'global' | 'tenant'>('global')
  const [editOwner, setEditOwner] = useState('')
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null)

  const listQueryKey = queryKeys.admin.services()
  const listQuery = useQuery({
    queryKey: listQueryKey,
    queryFn: () =>
      isPlatformAdmin
        ? servicesApi.listAll()
        : servicesApi.listForTenant(),
  })

  const createMutation = useMutation({
    mutationFn: (payload: RegisterServiceBody) => servicesApi.register(payload),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: listQueryKey })
      setShowCreate(false)
    },
  })

  const updateScopeMutation = useMutation({
    mutationFn: ({ serviceId, body }: { serviceId: string; body: { scope: 'global' | 'tenant'; owner_tenant_id?: string } }) =>
      servicesApi.updateScope(serviceId, body),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: listQueryKey })
      setEditTarget(null)
    },
  })

  const deleteMutation = useMutation({
    mutationFn: (serviceId: string) => servicesApi.delete(serviceId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: listQueryKey })
      setDeleteTarget(null)
    },
  })

  function handleCreateSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    const form = new FormData(e.currentTarget)
    const timeout = Number(form.get('timeout_ms'))
    const retries = form.get('max_retries') ? Number(form.get('max_retries')) : undefined
    const ownerTenant = (form.get('owner_tenant_id') as string)?.trim() || undefined
    createMutation.mutate({
      service_id: form.get('service_id') as string,
      endpoint_url: form.get('endpoint_url') as string,
      scope: form.get('scope') as 'global' | 'tenant',
      owner_tenant_id: ownerTenant,
      auth_method: form.get('auth_method') as string,
      timeout_ms: timeout,
      max_retries: retries,
      request_schema: form.get('request_schema') as string,
      response_schema: form.get('response_schema') as string,
    })
  }

  function openEditScope(row: ServiceRecord) {
    setEditTarget(row)
    setEditScope(row.scope)
    setEditOwner(row.owner_tenant_id ?? '')
  }

  function handleEditScopeSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    if (!editTarget) return
    updateScopeMutation.mutate({
      serviceId: editTarget.service_id,
      body: { scope: editScope, owner_tenant_id: editOwner.trim() || undefined },
    })
  }

  const items = listQuery.data?.items ?? []
  const rendererState: RendererState = listQuery.isLoading ? 'loading' : listQuery.isError ? classifyError(listQuery.error) : 'success'

  return (
    <div style={{ padding: '1.5rem' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '.75rem', marginBottom: '1.25rem' }}>
        <h2 style={{ margin: 0 }}>Services</h2>
        {/* CUSTOM: role-gate — Register button only for platform-admin */}
        {isPlatformAdmin && (
          <button
            type="button"
            onClick={() => setShowCreate(true)}
            style={{ marginLeft: 'auto', padding: '.45rem .9rem', background: '#0369a1', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
          >
            + Register service
          </button>
        )}
      </div>

      <div style={{ display: 'flex', gap: '.65rem', marginBottom: '1rem' }}>
        <input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="service ID or endpoint"
          style={{ padding: '.45rem .6rem', border: '1px solid #cbd5e1', borderRadius: '4px', flex: '1 1 200px' }}
        />
        <select
          value={scope}
          onChange={(e) => setScope(e.target.value)}
          style={{ padding: '.45rem .6rem', border: '1px solid #cbd5e1', borderRadius: '4px' }}
        >
          <option value="">All</option>
          <option value="global">Global</option>
          <option value="tenant">Tenant-scoped</option>
        </select>
      </div>

      <QueryStateBoundary
        state={rendererState}
        onRetry={() => { void listQuery.refetch() }}
        columns={[{ widthPercent: 20 }, { widthPercent: 10 }, { widthPercent: 30 }, { widthPercent: 15 }, { widthPercent: 12 }, { widthPercent: 13 }]}
      >
      {!listQuery.isLoading && !listQuery.isError && (
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '.85rem' }}>
          <thead>
            <tr style={{ background: '#f1f5f9', textAlign: 'left' }}>
              <th style={{ padding: '.6rem .8rem' }}>Service ID</th>
              <th style={{ padding: '.6rem .8rem' }}>Scope</th>
              <th style={{ padding: '.6rem .8rem' }}>Endpoint</th>
              <th style={{ padding: '.6rem .8rem' }}>Auth</th>
              <th style={{ padding: '.6rem .8rem' }}>Timeout (ms)</th>
              <th style={{ padding: '.6rem .8rem' }}>Retries</th>
              {/* CUSTOM: role-gate — owner_tenant column only for platform-admin */}
              {isPlatformAdmin && <th style={{ padding: '.6rem .8rem' }}>Owner tenant</th>}
              {isPlatformAdmin && <th style={{ padding: '.6rem .8rem' }}>Actions</th>}
            </tr>
          </thead>
          <tbody>
            {items
              .filter((row) => {
                const q = search.toLowerCase()
                const matchSearch = !q || row.service_id.toLowerCase().includes(q) || row.endpoint_url.toLowerCase().includes(q)
                const matchScope = !scope || row.scope === scope
                return matchSearch && matchScope
              })
              .map((row) => (
                <tr key={row.service_id} style={{ borderBottom: '1px solid #e2e8f0' }}>
                  <td style={{ padding: '.55rem .8rem', fontFamily: 'monospace' }}>{row.service_id}</td>
                  <td style={{ padding: '.55rem .8rem' }}>{row.scope}</td>
                  <td style={{ padding: '.55rem .8rem', maxWidth: '220px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{row.endpoint_url}</td>
                  <td style={{ padding: '.55rem .8rem' }}>{row.required_auth}</td>
                  <td style={{ padding: '.55rem .8rem' }}>{row.timeout_ms}</td>
                  <td style={{ padding: '.55rem .8rem' }}>{row.max_retries}</td>
                  {/* CUSTOM: role-gate — owner_tenant cell only for platform-admin */}
                  {isPlatformAdmin && (
                    <td style={{ padding: '.55rem .8rem', fontFamily: 'monospace', fontSize: '.8rem', color: '#64748b' }}>
                      {row.owner_tenant_id ?? '—'}
                    </td>
                  )}
                  {isPlatformAdmin && (
                    <td style={{ padding: '.55rem .8rem' }}>
                      <button
                        type="button"
                        onClick={() => openEditScope(row)}
                        style={{ marginRight: '.5rem', padding: '.3rem .6rem', fontSize: '.78rem', cursor: 'pointer' }}
                      >
                        Edit scope
                      </button>
                      <button
                        type="button"
                        onClick={() => setDeleteTarget(row.service_id)}
                        style={{ padding: '.3rem .6rem', fontSize: '.78rem', cursor: 'pointer', color: '#9f1239' }}
                      >
                        Delete
                      </button>
                    </td>
                  )}
                </tr>
              ))}
            {items.length === 0 && (
              <tr>
                <td colSpan={isPlatformAdmin ? 8 : 6} style={{ padding: '1rem .8rem', color: '#64748b', textAlign: 'center' }}>
                  No services found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      )}
      </QueryStateBoundary>

      {/* CUSTOM: Register service modal (platform-admin only) */}
      {showCreate && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 50 }}>
          <div style={{ background: '#fff', borderRadius: '8px', padding: '1.5rem', width: '480px', maxHeight: '90vh', overflowY: 'auto' }}>
            <h3 style={{ margin: '0 0 1rem' }}>Register service</h3>
            <form onSubmit={handleCreateSubmit}>
              {([
                { name: 'service_id', label: 'Service ID', type: 'text', required: true },
                { name: 'endpoint_url', label: 'Endpoint URL', type: 'text', required: true },
              ] as const).map((f) => (
                <label key={f.name} style={{ display: 'block', marginBottom: '.75rem' }}>
                  <span style={{ display: 'block', marginBottom: '.25rem', fontWeight: 500 }}>{f.label}</span>
                  <input type={f.type} name={f.name} required={f.required} style={{ width: '100%', padding: '.45rem .6rem', border: '1px solid #cbd5e1', borderRadius: '4px', boxSizing: 'border-box' }} />
                </label>
              ))}
              <label style={{ display: 'block', marginBottom: '.75rem' }}>
                <span style={{ display: 'block', marginBottom: '.25rem', fontWeight: 500 }}>Scope</span>
                <select name="scope" required style={{ width: '100%', padding: '.45rem .6rem', border: '1px solid #cbd5e1', borderRadius: '4px' }}>
                  <option value="global">Global (all tenants)</option>
                  <option value="tenant">Tenant-scoped</option>
                </select>
              </label>
              <label style={{ display: 'block', marginBottom: '.75rem' }}>
                <span style={{ display: 'block', marginBottom: '.25rem', fontWeight: 500 }}>Owner tenant ID</span>
                <input type="text" name="owner_tenant_id" style={{ width: '100%', padding: '.45rem .6rem', border: '1px solid #cbd5e1', borderRadius: '4px', boxSizing: 'border-box' }} />
              </label>
              <label style={{ display: 'block', marginBottom: '.75rem' }}>
                <span style={{ display: 'block', marginBottom: '.25rem', fontWeight: 500 }}>Auth method</span>
                <select name="auth_method" required style={{ width: '100%', padding: '.45rem .6rem', border: '1px solid #cbd5e1', borderRadius: '4px' }}>
                  <option value="NONE">None</option>
                  <option value="API_KEY">API Key</option>
                  <option value="OAUTH2">OAuth2</option>
                  <option value="MUTUAL_TLS">Mutual TLS</option>
                </select>
              </label>
              {([
                { name: 'timeout_ms', label: 'Timeout (ms)', required: true },
                { name: 'max_retries', label: 'Max retries', required: false },
              ] as const).map((f) => (
                <label key={f.name} style={{ display: 'block', marginBottom: '.75rem' }}>
                  <span style={{ display: 'block', marginBottom: '.25rem', fontWeight: 500 }}>{f.label}</span>
                  <input type="number" name={f.name} required={f.required} min={0} style={{ width: '100%', padding: '.45rem .6rem', border: '1px solid #cbd5e1', borderRadius: '4px', boxSizing: 'border-box' }} />
                </label>
              ))}
              {([
                { name: 'request_schema', label: 'Request schema' },
                { name: 'response_schema', label: 'Response schema' },
              ] as const).map((f) => (
                <label key={f.name} style={{ display: 'block', marginBottom: '.75rem' }}>
                  <span style={{ display: 'block', marginBottom: '.25rem', fontWeight: 500 }}>{f.label}</span>
                  <textarea name={f.name} required rows={3} style={{ width: '100%', padding: '.45rem .6rem', border: '1px solid #cbd5e1', borderRadius: '4px', boxSizing: 'border-box', fontFamily: 'monospace', fontSize: '.82rem' }} />
                </label>
              ))}
              {createMutation.isError && (
                <div style={{ padding: '.6rem', background: '#fff1f2', border: '1px solid #fca5a5', borderRadius: '4px', color: '#9f1239', marginBottom: '.75rem', fontSize: '.85rem' }}>
                  Failed to register service.
                </div>
              )}
              <div style={{ display: 'flex', gap: '.5rem', justifyContent: 'flex-end' }}>
                <button type="button" onClick={() => setShowCreate(false)} style={{ padding: '.45rem .9rem', cursor: 'pointer' }}>Cancel</button>
                <button type="submit" disabled={createMutation.isPending} style={{ padding: '.45rem .9rem', background: '#0369a1', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
                  {createMutation.isPending ? 'Registering…' : 'Register'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* CUSTOM: Edit scope modal (platform-admin only) */}
      {editTarget && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 50 }}>
          <div style={{ background: '#fff', borderRadius: '8px', padding: '1.5rem', width: '380px' }}>
            <h3 style={{ margin: '0 0 1rem' }}>Edit scope — {editTarget.service_id}</h3>
            <form onSubmit={handleEditScopeSubmit}>
              <label style={{ display: 'block', marginBottom: '.75rem' }}>
                <span style={{ display: 'block', marginBottom: '.25rem', fontWeight: 500 }}>Scope</span>
                <select value={editScope} onChange={(e) => setEditScope(e.target.value as 'global' | 'tenant')} style={{ width: '100%', padding: '.45rem .6rem', border: '1px solid #cbd5e1', borderRadius: '4px' }}>
                  <option value="global">Global (all tenants)</option>
                  <option value="tenant">Tenant-scoped</option>
                </select>
              </label>
              <label style={{ display: 'block', marginBottom: '.75rem' }}>
                <span style={{ display: 'block', marginBottom: '.25rem', fontWeight: 500 }}>Owner tenant ID</span>
                <input type="text" value={editOwner} onChange={(e) => setEditOwner(e.target.value)} style={{ width: '100%', padding: '.45rem .6rem', border: '1px solid #cbd5e1', borderRadius: '4px', boxSizing: 'border-box' }} />
              </label>
              {updateScopeMutation.isError && (
                <div style={{ padding: '.6rem', background: '#fff1f2', border: '1px solid #fca5a5', borderRadius: '4px', color: '#9f1239', marginBottom: '.75rem', fontSize: '.85rem' }}>
                  Failed to update scope.
                </div>
              )}
              <div style={{ display: 'flex', gap: '.5rem', justifyContent: 'flex-end' }}>
                <button type="button" onClick={() => setEditTarget(null)} style={{ padding: '.45rem .9rem', cursor: 'pointer' }}>Cancel</button>
                <button type="submit" disabled={updateScopeMutation.isPending} style={{ padding: '.45rem .9rem', background: '#0369a1', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
                  {updateScopeMutation.isPending ? 'Saving…' : 'Save'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* CUSTOM: Delete confirmation modal (platform-admin only) */}
      {deleteTarget && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 50 }}>
          <div style={{ background: '#fff', borderRadius: '8px', padding: '1.5rem', width: '380px' }}>
            <h3 style={{ margin: '0 0 .75rem' }}>Remove service?</h3>
            <p style={{ margin: '0 0 1rem', fontSize: '.9rem', color: '#475569' }}>
              Active definitions referencing <strong>{deleteTarget}</strong> will be listed. This cannot be undone.
            </p>
            {deleteMutation.isError && (
              <div style={{ padding: '.6rem', background: '#fff1f2', border: '1px solid #fca5a5', borderRadius: '4px', color: '#9f1239', marginBottom: '.75rem', fontSize: '.85rem' }}>
                Failed to delete service. It may be referenced by active definitions.
              </div>
            )}
            <div style={{ display: 'flex', gap: '.5rem', justifyContent: 'flex-end' }}>
              <button type="button" onClick={() => setDeleteTarget(null)} style={{ padding: '.45rem .9rem', cursor: 'pointer' }}>Cancel</button>
              <button
                type="button"
                disabled={deleteMutation.isPending}
                onClick={() => deleteMutation.mutate(deleteTarget)}
                style={{ padding: '.45rem .9rem', background: '#dc2626', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
              >
                {deleteMutation.isPending ? 'Deleting…' : 'Delete'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
