import { expect, test } from '@playwright/test'
import { randomUUID } from 'crypto'
import * as fs from 'fs'
import * as path from 'path'
import { getKeycloakToken, loginWithToken } from './helpers'

const SCREENSHOTS_DIR = 'tests/screenshots'
const API_BASE_URL = process.env.BPM_TEST_URL ?? 'http://127.0.0.1:8080'
const KEYCLOAK_BASE_URL = process.env.BPM_IDP_BASE_URL ?? 'http://127.0.0.1:8081'
const KEYCLOAK_DISCOVERY_URL = `${KEYCLOAK_BASE_URL}/realms/bpm-default/.well-known/openid-configuration`
const API_PREFIX = '/api/v1'

function getEnvOrDefault(name: string, fallback: string): string {
  const value = process.env[name]
  return value && value.trim() ? value : fallback
}

function getAdminCredentials(): { username: string; password: string } {
  return {
    username: getEnvOrDefault('BPM_E2E_ADMIN_USERNAME', 'admin-user'),
    password: getEnvOrDefault('BPM_E2E_ADMIN_PASSWORD', 'admin-pass'),
  }
}

function shotPath(name: string): string {
  const dir = path.resolve(SCREENSHOTS_DIR)
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
  return path.join(dir, `F6-${name}.png`)
}

async function shot(page: import('@playwright/test').Page, name: string): Promise<void> {
  await page.screenshot({ path: shotPath(name), fullPage: true })
}

function decodeJwtPayload(token: string): { sub?: string; preferred_username?: string; [key: string]: unknown } {
  const parts = token.split('.')
  if (parts.length !== 3) throw new Error('Invalid JWT token')
  return JSON.parse(Buffer.from(parts[1], 'base64').toString('utf-8')) as { sub?: string; preferred_username?: string; [key: string]: unknown }
}

async function assertServiceReadiness(
  request: import('@playwright/test').APIRequestContext,
): Promise<void> {
  const backendHealth = await request.fetch(`${API_BASE_URL}/health/ready`)
  if (!backendHealth.ok()) {
    throw new Error(`Backend readiness check failed (${backendHealth.status()}) at ${API_BASE_URL}/health/ready`)
  }

  const idpHealth = await request.fetch(KEYCLOAK_DISCOVERY_URL)
  if (!idpHealth.ok()) {
    throw new Error(`Keycloak readiness check failed (${idpHealth.status()}) at ${KEYCLOAK_DISCOVERY_URL}`)
  }
}

async function createDlqFixtureDefinition(
  request: import('@playwright/test').APIRequestContext,
  token: string,
  assigneeUserId: string,
  fixtureId: string,
): Promise<string> {
  const createResponse = await request.post(`${API_BASE_URL}${API_PREFIX}/definitions`, {
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    data: {
      name: `F6 DLQ Fixture ${fixtureId}`,
      version: '1.0.0',
      description: 'F6 DLQ UI fixture definition generated by E2E setup',
      stage: null,
      graph: {
        nodes: [
          { id: 'start', node_type: 'START', label: 'Start', attributes: null },
          {
            id: 'task-1',
            node_type: 'HUMAN_TASK',
            label: 'Approve payload',
            attributes: JSON.stringify({
              role: 'reviewer',
              assignee_type: 'USER',
              assignee_ref: assigneeUserId,
              form_schema: {
                type: 'object',
                properties: {
                  approved: { type: 'boolean', title: 'Approved' },
                  comment: { type: 'string', title: 'Comment' },
                },
                required: ['approved', 'comment'],
              },
            }),
          },
          {
            id: 'service-1',
            node_type: 'SERVICE_TASK',
            label: 'Failing webhook simulation',
            attributes: JSON.stringify({
              endpoint: 'http://127.0.0.1:65535/fail-fast',
              method: 'POST',
              timeout_ms: 150,
              retry_limit: 0,
            }),
          },
          { id: 'end', node_type: 'END', label: 'End', attributes: null },
        ],
        edges: [
          { id: 'e1', source: 'start', target: 'task-1', condition: null, is_default: false },
          { id: 'e2', source: 'task-1', target: 'service-1', condition: null, is_default: false },
          { id: 'e3', source: 'service-1', target: 'end', condition: null, is_default: false },
        ],
      },
    },
  })

  if (!createResponse.ok()) {
    const body = await createResponse.text()
    throw new Error(`F6 fixture definition create failed (${createResponse.status()}): ${body}`)
  }

  const created = (await createResponse.json()) as { id?: string }
  if (!created.id) throw new Error('F6 fixture definition create response missing id')

  const activateResponse = await request.post(`${API_BASE_URL}${API_PREFIX}/definitions/${created.id}/activate`, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })
  if (!activateResponse.ok()) {
    const body = await activateResponse.text()
    throw new Error(`F6 fixture definition activate failed (${activateResponse.status()}): ${body}`)
  }

  return created.id
}

async function startFixtureInstance(
  request: import('@playwright/test').APIRequestContext,
  token: string,
  definitionId: string,
  fixtureId: string,
): Promise<string> {
  const response = await request.post(`${API_BASE_URL}${API_PREFIX}/instances`, {
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    data: {
      definition_id: definitionId,
      correlation_key: `f6-dlq-${fixtureId}`,
      initial_variables: {
        source: 'f6-dlq-e2e',
        fixture_id: fixtureId,
      },
    },
  })

  if (!response.ok()) {
    const body = await response.text()
    throw new Error(`F6 fixture instance start failed (${response.status()}): ${body}`)
  }

  const payload = (await response.json()) as { instance_id?: string }
  if (!payload.instance_id) throw new Error('F6 fixture start response missing instance_id')
  return payload.instance_id
}

async function waitForTaskId(
  request: import('@playwright/test').APIRequestContext,
  token: string,
  instanceId: string,
): Promise<string> {
  const deadline = Date.now() + 20_000
  while (Date.now() < deadline) {
    const response = await request.get(`${API_BASE_URL}${API_PREFIX}/tasks`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
      params: {
        instance_id: instanceId,
      },
    })

    if (response.ok()) {
      const payload = (await response.json()) as { items?: Array<{ id?: string }> }
      const taskId = payload.items?.[0]?.id
      if (taskId) return taskId
    }

    await new Promise((resolve) => setTimeout(resolve, 500))
  }

  throw new Error(`F6 fixture task did not appear for instance ${instanceId}`)
}

async function completeFixtureTask(
  request: import('@playwright/test').APIRequestContext,
  token: string,
  taskId: string,
): Promise<void> {
  const response = await request.post(`${API_BASE_URL}${API_PREFIX}/tasks/${taskId}/complete`, {
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    data: {
      output_variables: {
        approved: true,
        comment: 'trigger service task failure for dlq fixture',
      },
    },
  })

  if (!response.ok()) {
    const body = await response.text()
    throw new Error(`F6 fixture task completion failed (${response.status()}): ${body}`)
  }
}

async function fetchDlqItems(
  request: import('@playwright/test').APIRequestContext,
  token: string,
): Promise<Array<{ id: string; instance_id?: string | null }>> {
  const response = await request.get(`${API_BASE_URL}/dlq`, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
    params: {
      page_size: '50',
    },
  })

  if (!response.ok()) {
    const body = await response.text()
    throw new Error(`F6 fixture failed to list DLQ items (${response.status()}): ${body}`)
  }

  const payload = (await response.json()) as { items?: Array<{ id?: string; instance_id?: string | null }> }
  const items = Array.isArray(payload.items) ? payload.items : []
  return items
    .filter((item): item is { id: string; instance_id?: string | null } => typeof item.id === 'string' && item.id.length > 0)
}

async function waitForNewDlqItem(
  request: import('@playwright/test').APIRequestContext,
  token: string,
  previousIds: Set<string>,
  fixtureInstanceId: string,
): Promise<{ id: string; instance_id?: string | null }> {
  const deadline = Date.now() + 20_000
  while (Date.now() < deadline) {
    const items = await fetchDlqItems(request, token)
    for (const item of items) {
      if (previousIds.has(item.id)) continue
      if (item.instance_id !== fixtureInstanceId) continue
      return item
    }

    await new Promise((resolve) => setTimeout(resolve, 500))
  }

  throw new Error('F6 fixture did not produce a new actionable DLQ item with instance context')
}

async function ensureActionableDlqFixture(
  request: import('@playwright/test').APIRequestContext,
  token: string,
): Promise<{ fixtureId: string; definitionId: string; instanceId: string; dlqId: string }> {
  const jwt = decodeJwtPayload(token)
  const assigneeUserId = typeof jwt.sub === 'string' && jwt.sub.length > 0 ? jwt.sub : 'admin-user'
  const baselineItems = await fetchDlqItems(request, token)
  const baselineIds = new Set(baselineItems.map((item) => item.id))
  const fixtureId = randomUUID()

  const definitionId = await createDlqFixtureDefinition(request, token, assigneeUserId, fixtureId)
  const instanceId = await startFixtureInstance(request, token, definitionId, fixtureId)
  const taskId = await waitForTaskId(request, token, instanceId)
  await completeFixtureTask(request, token, taskId)
  const dlqItem = await waitForNewDlqItem(request, token, baselineIds, instanceId)

  return { fixtureId, definitionId, instanceId, dlqId: dlqItem.id }
}

async function discardDlqFixture(
  request: import('@playwright/test').APIRequestContext,
  token: string,
  dlqId: string,
): Promise<void> {
  const response = await request.post(`${API_BASE_URL}/dlq/${dlqId}/discard`, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })

  if (![200, 202, 204, 404].includes(response.status())) {
    const body = await response.text()
    throw new Error(`F6 fixture DLQ discard failed for ${dlqId} (${response.status()}): ${body}`)
  }
}

async function cancelFixtureInstance(
  request: import('@playwright/test').APIRequestContext,
  token: string,
  instanceId: string,
): Promise<void> {
  const response = await request.post(`${API_BASE_URL}${API_PREFIX}/instances/${instanceId}/cancel`, {
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    data: {
      reason: 'F6 DLQ E2E cleanup',
    },
  })

  if (![200, 202, 204, 404].includes(response.status())) {
    const body = await response.text()
    throw new Error(`F6 fixture instance cancel failed for ${instanceId} (${response.status()}): ${body}`)
  }
}

async function deleteFixtureDefinition(
  request: import('@playwright/test').APIRequestContext,
  token: string,
  definitionId: string,
): Promise<void> {
  const response = await request.delete(`${API_BASE_URL}${API_PREFIX}/definitions/${definitionId}`, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })

  if (![200, 202, 204, 404].includes(response.status())) {
    const body = await response.text()
    throw new Error(`F6 fixture definition delete failed for ${definitionId} (${response.status()}): ${body}`)
  }
}

async function navigateSpa(page: import('@playwright/test').Page, targetPath: string): Promise<void> {
  await page.evaluate((nextPath) => {
    window.history.pushState({}, '', nextPath)
    window.dispatchEvent(new PopStateEvent('popstate'))
  }, targetPath)
  await page.waitForURL((url) => `${url.pathname}${url.search}` === targetPath, { timeout: 10_000 })
}

async function openDlqAndAssertRows(page: import('@playwright/test').Page, searchText?: string): Promise<void> {
  await navigateSpa(page, '/dlq')
  await expect(page.getByRole('heading', { name: 'Dead-Letter Queue' })).toBeVisible({ timeout: 10_000 })
  await expect(page.getByTestId('dlq-table')).toBeVisible()

  if (searchText) {
    const searchInput = page.getByTestId('dlq-filter-search')
    await searchInput.fill(searchText)
    await page.getByTestId('dlq-filter-apply').click()
  }

  const rows = page.locator('[data-testid^="dlq-row-"]')
  const rowCount = await rows.count()
  if (rowCount === 0) {
    await shot(page, 'DLQ-empty-state-blocker')
    throw new Error('DLQ fixture precondition failed: expected at least one DLQ row to validate DLQ-UI-01..04')
  }
}

async function firstRowActionIds(page: import('@playwright/test').Page): Promise<{ detailsButtonId: string; retryButtonId: string; discardButtonId: string }> {
  const rowTestId = await page.locator('[data-testid^="dlq-row-"]').first().getAttribute('data-testid')
  if (!rowTestId) {
    throw new Error('Missing DLQ row test id for first row')
  }

  return {
    detailsButtonId: rowTestId.replace('dlq-row-', 'dlq-details-'),
    retryButtonId: rowTestId.replace('dlq-row-', 'dlq-retry-'),
    discardButtonId: rowTestId.replace('dlq-row-', 'dlq-discard-'),
  }
}

test.describe('F6 DLQ UI (DLQ-UI-01..04)', () => {
  let adminToken = ''
  let fixtureDefinitionId = ''
  let fixtureInstanceId = ''
  let fixtureDlqId = ''

  test.beforeEach(async ({ request }) => {
    fixtureDefinitionId = ''
    fixtureInstanceId = ''
    fixtureDlqId = ''

    await assertServiceReadiness(request)
    const creds = getAdminCredentials()
    adminToken = await getKeycloakToken(request, creds.username, creds.password)
    const fixture = await ensureActionableDlqFixture(request, adminToken)
    fixtureDefinitionId = fixture.definitionId
    fixtureInstanceId = fixture.instanceId
    fixtureDlqId = fixture.dlqId
  })

  test.afterEach(async ({ request }) => {
    if (!adminToken) return

    const cleanupErrors: string[] = []

    if (fixtureDlqId) {
      try {
        await discardDlqFixture(request, adminToken, fixtureDlqId)
      } catch (error) {
        cleanupErrors.push(`discard dlq ${fixtureDlqId}: ${String(error)}`)
      }
    }

    if (fixtureInstanceId) {
      try {
        await cancelFixtureInstance(request, adminToken, fixtureInstanceId)
      } catch (error) {
        cleanupErrors.push(`cancel instance ${fixtureInstanceId}: ${String(error)}`)
      }
    }

    if (fixtureDefinitionId) {
      try {
        await deleteFixtureDefinition(request, adminToken, fixtureDefinitionId)
      } catch (error) {
        cleanupErrors.push(`delete definition ${fixtureDefinitionId}: ${String(error)}`)
      }
    }

    fixtureDefinitionId = ''
    fixtureInstanceId = ''
    fixtureDlqId = ''

    if (cleanupErrors.length > 0) {
      throw new Error(`F6 fixture cleanup failed (${cleanupErrors.join(' | ')})`)
    }
  })

  test('TC-DLQ-UI-01-E2E-01: DLQ list renders required columns and rows', async ({ page }) => {
    await loginWithToken(page, adminToken)
    await openDlqAndAssertRows(page, fixtureDlqId)

    await expect(page.getByRole('columnheader', { name: 'Source' })).toBeVisible()
    await expect(page.getByRole('columnheader', { name: 'Instance' })).toBeVisible()
    await expect(page.getByRole('columnheader', { name: 'Reason' })).toBeVisible()
    await expect(page.getByRole('columnheader', { name: 'Retry count' })).toBeVisible()
    await expect(page.getByRole('columnheader', { name: 'Created' })).toBeVisible()
    await expect(page.getByRole('columnheader', { name: 'Status' })).toBeVisible()
    await shot(page, 'DLQ-UI-01-list')
  })

  test('TC-DLQ-UI-02-E2E-01: DLQ detail panel shows failure reason, retry history, and payload context', async ({ page }) => {
    await loginWithToken(page, adminToken)
    await openDlqAndAssertRows(page, fixtureDlqId)

    const { detailsButtonId } = await firstRowActionIds(page)
    await page.getByTestId(detailsButtonId).click()
    await expect(page.getByTestId('dlq-detail-panel')).toBeVisible()
    await expect(page.getByText('Full failure reason')).toBeVisible()
    await expect(page.getByText('Retry history')).toBeVisible()
    await expect(page.getByText('Context JSON')).toBeVisible()
    await expect(page.getByText('Source payload')).toBeVisible()
    await shot(page, 'DLQ-UI-02-detail-panel')
  })

  test('TC-DLQ-UI-03-E2E-01: Retry action attempts POST /dlq/:id/retry and shows retrying or error feedback', async ({ page }) => {
    await loginWithToken(page, adminToken)
    await openDlqAndAssertRows(page, fixtureDlqId)

    const { retryButtonId } = await firstRowActionIds(page)
    await expect(page.getByTestId(retryButtonId)).toBeVisible({ timeout: 10_000 })
    await page.getByTestId(retryButtonId).click()

    const retryIndicator = page.locator('[data-testid^="dlq-row-"]').first().getByText(/retrying/i)
    const actionError = page.getByText('Retry failed. Please try again.')

    await Promise.race([
      retryIndicator.waitFor({ state: 'visible', timeout: 10_000 }),
      actionError.waitFor({ state: 'visible', timeout: 10_000 }),
    ])
    await shot(page, 'DLQ-UI-03-retry-attempt')
  })

  test('TC-DLQ-UI-04-E2E-01: Discard action opens confirmation dialog with cancellation warning context', async ({ page }) => {
    await loginWithToken(page, adminToken)
    await openDlqAndAssertRows(page, fixtureDlqId)

    const { discardButtonId } = await firstRowActionIds(page)
    await expect(page.getByTestId(discardButtonId)).toBeVisible({ timeout: 10_000 })
    await page.getByTestId(discardButtonId).click()

    await expect(page.getByTestId('dlq-discard-dialog')).toBeVisible()
    await expect(page.getByText('Discard this DLQ item?')).toBeVisible()
    await expect(page.getByText('Discarding may cancel the associated instance.')).toBeVisible()
    await shot(page, 'DLQ-UI-04-discard-confirmation')
    await page.getByRole('button', { name: 'Cancel' }).click()
    await expect(page.getByTestId('dlq-discard-dialog')).toBeHidden()
  })
})
