defmodule Letflow.Routers.SolutionPacks do
  @moduledoc """
  PROVENANCE (historical, not current decision authority):
  Solution-pack export/install sub-router (REQ-078, design
  `lib/letflow/design/req078-supporting-routes.md` §8). Ports
  `src/api/routes/solution_packs.zig`'s `handleExport` (L29) and
  `handleInstall` (L110). Mounted at `/solution-packs` by
  `Letflow.Plugs.ApiPipeline`, so the full paths under `/api/v1` are
  `/api/v1/solution-packs/export` and `/api/v1/solution-packs/install`.

  | Handler | Method/path                     | Delegate                                     | Auth | Response                    |
  |---------|---------------------------------|----------------------------------------------|------|-----------------------------|
  | export  | `POST /solution-packs/export`   | `Letflow.Definitions.SolutionPack.export/3`  | none in this requirement (REQ-131) | 200, the pack document |
  | install | `POST /solution-packs/install`  | `Letflow.Definitions.SolutionPack.install/3` | none in this requirement (REQ-131) | 200, the install result |

  ## The R-Co path's `{tenant_id}` segment is DROPPED (INV-1)

  R-Co serves these at
  `POST /api/v1/tenants/{tenant_id}/solution-packs/export` and `.../install` —
  the tenant is **caller-supplied in the path**. Letflow drops that segment
  entirely.

  > **The tenant a solution-pack request reads from and writes into is derived
  > solely from `Letflow.Api.Context.scoped_repo_opts/1`, i.e. solely from
  > `conn.assigns[:auth_context][:tenant_id]`. No tenant identifier appears
  > anywhere in these two URLs, so no caller-supplied tenant value can reach a
  > `:prefix` — not by precedence, not by fallback, not by a future
  > refactor.**

  Keeping the segment "for path fidelity" and 404-ing on a mismatch was
  considered and rejected: a path segment that is authoritative for nothing is
  a standing invitation for a later reader to "wire it up", which would be a
  cross-tenant write. It was rejected a second time because `/tenants` is
  already forwarded to `Letflow.Routers.Tenants`, so that shape would put pack
  export/install inside the PLATFORM_ADMIN-only tenant-administration router —
  the wrong permission neighbourhood.

  ## INV-1, both directions

  **Export** reads only through `opts[:prefix]`. A `definition_id` owned by
  another tenant is invisible in the caller's schema and can only produce a
  422 whose detail deliberately **does not echo the id** — echoing it would
  confirm to a prober that the id exists somewhere (INV-5).

  **Install** writes every definition and every `variable_schemas` row with
  that same prefix. The single exception is the one `solution_pack_installs`
  row, whose table is global by REQ-041's design; its `tenant_id` is *derived*
  from the resolved prefix via
  `Letflow.TenantProvisioning.tenant_id_for_schema_name/1` inside the context
  module, never accepted as a caller-supplied field.

  ## The `variable_schemas` write path (AC8)

  Install writes `variable_schemas` rows **only** through
  `Letflow.Definitions.register_variable_schemas/3` — the single shared
  registration function REQ-082's definition import also calls. **No second
  insert path into that table exists in the route layer, or anywhere else in
  `lib/`.** This module performs no `Repo` call of any kind; naming the table
  and the function here is a pointer to the single path, not a second one.

  ## Deliberate non-ports, each with its reason and owner

    PROVENANCE (historical, not current decision authority):
    * **`service_catalog_entries` / `409 CATALOG_CONFLICT`**
      (`solution_packs.zig:135`) — Letflow has no service catalog;
      `services.zig` owns stage **S6**. Export emits `[]`; install rejects a
      non-empty array with **422** rather than silently discarding
      tenant-supplied content.
    PROVENANCE (historical, not current decision authority):
    * **`MODULE_NON_EXPORTABLE`** (`solution_packs.zig:83`) — no
      process-module packaging in Letflow; `process_modules.zig` owns stage
      **S5**.
    PROVENANCE (historical, not current decision authority):
    * **`409 TenantInactive`** (`solution_packs.zig:127-134`) — already
      enforced **upstream**: `Letflow.Plugs.TenantStatus` runs in
      `Letflow.Plugs.ApiPipeline` before any sub-router and rejects an
      inactive tenant with `403 tenant_inactive` for every method. A 409
      branch here could never fire.
    PROVENANCE (historical, not current decision authority):
    * **`409 VARIABLE_SCHEMA_CONFLICT`** (`solution_packs.zig:136`) —
      **unreachable in Letflow**, not merely unported. Install creates every
      definition it writes schemas for, and `ProcessDefinition`'s primary key
      is autogenerated, so every `(definition_id, variable_key)` pair it
      writes has a brand-new id half. The proof is in
      `Letflow.Definitions.SolutionPack`'s moduledoc, **together with the
      standing condition that invalidates it**: if a later requirement adds an
      install mode that attaches variable schemas to a *pre-existing*
      definition, the conflict becomes reachable and must be reinstated.
    PROVENANCE (historical, not current decision authority):
    * **R-Co's idempotent re-install** (`buildIdempotentResult`,
      `src/solution/store.zig:682`, called from `:337`) — R-Co returns a
      synthetic success for an already-installed pack. **Letflow returns 409**,
      from `uq_solution_pack_install_active` and/or from
      `{:error, :duplicate_name_version}`, and aborts the whole install. If
      idempotent re-install is wanted it needs its own requirement.
    * **503 `PoolExhausted`** — Ecto/DBConnection surfaces pool exhaustion as
      a raised `DBConnection.ConnectionError`, not an `{:error, :pool_exhausted}`
      tuple, so there is no tuple to match and a 503 clause would be a branch
      nothing can reach.

  ## Authorization gap — REQ-131 closes it

  PROVENANCE (historical, not current decision authority):
  Neither route calls `Letflow.Api.Authorization.evaluate_access/2`.
  `endpoint_policy_key/2` has **no clause** for `POST /solution-packs/*` —
  there is no existing policy clause to extend (R-Co's `authorization.zig`
  has no entry for these paths either), and deciding what
  permission a pack install requires is a policy question that belongs to
  **REQ-130/REQ-131**, not to a
  route-port requirement. Inventing a route-local permission check here was
  explicitly ruled out (REQ-069's whole point is one matrix).

  These endpoints are therefore **authenticated** (via
  `Letflow.Plugs.AuthPipeline`) and **tenant-scoped** (via
  `scoped_repo_opts/1`), but **not permission-gated**. **REQ-131 is the
  closer.** This gap is stated here so it is visible rather than silent.

  ## Ordering guarantee

  Honours the contract stated in `Letflow.Routers.Tenants`'s moduledoc section
  **"Ordering guarantee (design §6.1)"**: no `Repo` call of any kind —
  including a pre-fetch read — happens before the preamble has resolved the
  scoped prefix. Here that is structural rather than merely observed: **this
  module performs no `Repo` call at all**; every read and write is inside
  `Letflow.Definitions.SolutionPack`, which cannot be reached without the
  prefix, because the prefix is the `opts` argument.

  PROVENANCE (historical, not current decision authority):
  ## `sandbox_access.zig` is NOT ported by REQ-078

  PROVENANCE (historical, not current decision authority):
  Recorded here as the nearest module in the requirement.
  `src/api/routes/sandbox_access.zig` (181 lines) is deliberately excluded,
  for three independent reasons any one of which suffices: it exports no
  `handle*` entry point (its three public functions are guards a route calls,
  not a route); its only consumer is `routes/agent_sandboxes.zig`, the
  runtime-agent subsystem owning stage **post-S6**, so porting it in S4 would
  ship a guard with no S4 caller to guard (the REQ-056 partial-backing-subsystem
  failure mode); and `checkProbeRate` is rate limiting, which needs the
  per-tenant counter storage REQ-068's SCOPE BOUNDARY paragraph explicitly
  defers. It moves with `agent_sandboxes.zig` to post-S6 — see the group-(b)
  table in `docs/migration/stage-4-api-surface.md`.
  """

  use Letflow.Api.AuthorizedRouter

  alias Letflow.Api.Response
  alias Letflow.Api.Validation
  alias Letflow.Api.Validation.FieldConstraint
  alias Letflow.Api.Validation.FieldError
  alias Letflow.Definitions
  alias Letflow.Definitions.SolutionPack
  alias Letflow.TenantProvisioning

  # REQ-131: endpoint_policy_key/2 has no clause for either route (see
  # "Authorization gap" below) -- :DefinitionsRead/:DefinitionsCreate are
  # route-declared policy keys (both real endpoint_policy_key() values,
  # each already backed by a required_permission/1 clause -- :DefinitionsRead
  # and :DefinitionsWrite respectively), reusing the closest-matching
  # existing policy keys (export reads existing definitions, same
  # permission class as GET /definitions*; install creates new definitions
  # and their variable_schemas rows, same permission class as
  # POST /definitions), not derived from Authorization.endpoint_policy_key/2.
  # Both named on the enforcement test's explicit allowlist (design §4) --
  # flagged for REVIEWER as a judgment call, not silently decided.
  authz_post "/export", :DefinitionsRead do
    handle_export(conn)
  end

  authz_post "/install", :DefinitionsCreate do
    handle_install(conn)
  end

  # REQ-380 (design lib/letflow/design/req380-pack-update-review-apply-api.md
  # §3.1/§4.1): both reuse the closest-matching existing policy key, same
  # judgment call as /export and /install above -- update-review reads and
  # classifies only (:DefinitionsRead), update-apply mutates
  # pack_update_resolutions/solution_pack_artefact_bases
  # (:DefinitionsCreate -> :DefinitionsWrite). Flagged for REVIEWER, not
  # silently decided (design §3.1/§4.1, OQ-1).
  authz_post "/:pack_id/update-review", :DefinitionsRead do
    handle_update_review(conn, conn.params["pack_id"])
  end

  authz_post "/:pack_id/update-apply", :DefinitionsCreate do
    handle_update_apply(conn, conn.params["pack_id"])
  end

  match _ do
    Response.not_found(conn)
  end

  # ── POST /solution-packs/export (design §8.5) ─────────────────────────────

  @export_schema [
    %FieldConstraint{
      name: "definition_ids",
      required: true,
      type: :array,
      min_items: 1
    },
    %FieldConstraint{
      name: "version",
      required: false,
      type: :string,
      reject_empty_string: true,
      max_length: 64
    }
  ]

  defp handle_export(conn) do
    case object_body(conn) do
      :error ->
        Response.bad_request(conn, "invalid body")

      {:ok, body} ->
        case Validation.validate(@export_schema, body) do
          {:errors, field_errors} ->
            Response.send_problem(conn, Validation.problem(field_errors))

          {:ok, attrs} ->
            export_with_ids(conn, Map.get(attrs, "definition_ids"), Map.get(attrs, "version"))
        end
    end
  end

  # The FieldConstraint vocabulary has no per-element type rule, so the
  # "every id is a string" check (R-Co's `definition_id_must_be_string`) is
  # made here, after validate/2 has established that the field is a non-empty
  # array.
  defp export_with_ids(conn, definition_ids, version) do
    if Enum.all?(definition_ids, &is_binary/1) do
      case SolutionPack.export(definition_ids, version, conn.assigns.scoped_opts) do
        {:ok, document} ->
          Response.ok(conn, pack_document_map(document))

        {:error, {:definition_not_found, _id}} ->
          # INV-5: the detail must NOT echo the id -- doing so would confirm
          # to a prober that some id exists in some other tenant's schema.
          Response.unprocessable(conn, "definition not found")

        {:error, :empty_definition_ids} ->
          Response.unprocessable(conn, "definition_ids must not be empty")

        {:error, _common_error} ->
          Response.internal_error(conn)
      end
    else
      Response.unprocessable(conn, "definition_id must be a string")
    end
  end

  # ── POST /solution-packs/install (design §8.5) ────────────────────────────

  defp handle_install(conn) do
    case conn.body_params do
      empty when empty == %{} ->
        Response.bad_request(conn, "empty body")

      %{"_json" => _non_object} ->
        Response.unprocessable(conn, "invalid pack document")

      document when is_map(document) ->
        install_document(conn, document)

      _other ->
        Response.unprocessable(conn, "invalid pack document")
    end
  end

  defp install_document(conn, document) do
    case actor_id(conn) do
      actor_id when is_binary(actor_id) ->
        render_install(conn, SolutionPack.install(document, actor_id, conn.assigns.scoped_opts))

      # No user id on the auth context -- not a caller error, it means this
      # route was reached without `Letflow.Plugs.AuthPipeline` having done
      # its job. Never falls through to an unscoped write.
      nil ->
        Response.internal_error(conn)
    end
  end

  defp render_install(conn, {:ok, result}), do: Response.ok(conn, install_result_map(result))

  defp render_install(conn, {:error, :invalid_pack_document}),
    do: Response.unprocessable(conn, "invalid pack document")

  defp render_install(conn, {:error, {:unknown_schema_version, _actual}}),
    do: Response.unprocessable(conn, "invalid pack document")

  defp render_install(conn, {:error, :unsupported_pack_section}),
    do: Response.unprocessable(conn, "pack contains an unsupported section")

  # `key` is the caller's own submitted value, so echoing it is safe and
  # useful; `reason`/`path` are internal and are not echoed.
  defp render_install(conn, {:error, {:malformed_variable_schema, key, _reason}}),
    do: malformed_variable_schema(conn, key)

  defp render_install(conn, {:error, {:not_well_formed, key, _path}}),
    do: malformed_variable_schema(conn, key)

  defp render_install(conn, {:error, {:schema_too_deep, key}}),
    do:
      Response.unprocessable(
        conn,
        "variable schema #{inspect(key)} nesting exceeds the maximum depth"
      )

  defp render_install(conn, {:error, {:duplicate_variable_key, key}}),
    do: Response.unprocessable(conn, "duplicate variable_key #{inspect(key)} in pack document")

  # The index is deliberately NOT echoed -- it names a position in a document
  # the caller already holds, and a constant detail keeps the body stable.
  defp render_install(conn, {:error, {:blank_variable_key, _index}}),
    do: Response.unprocessable(conn, "variable_key must not be blank")

  # Same echo convention as `:blank_variable_key` above, and for the same two
  # reasons: the payload is an index into the caller's own document, and the
  # offending key itself is unfit to echo -- it is by definition longer than
  # the 255-byte column, so echoing it would put an unbounded caller-controlled
  # blob into the response body. The limit is named instead.
  defp render_install(conn, {:error, {:variable_key_too_long, _index}}),
    do: Response.unprocessable(conn, "variable_key must not exceed 255 bytes")

  defp render_install(conn, {:error, :duplicate_pack_install}),
    do: Response.conflict(conn, "pack already installed")

  defp render_install(conn, {:error, :duplicate_name_version}),
    do: Response.conflict(conn, "definition already exists")

  # Route-construction bugs, not caller errors -- same treatment as
  # `Letflow.Routers.Instances`'s `:missing_actor_id`.
  defp render_install(conn, {:error, reason})
       when reason in [:missing_prefix, :invalid_definition_id, :invalid_schema_name],
       do: Response.internal_error(conn)

  defp render_install(conn, {:error, reason})
       when reason in [
              :tenant_id_not_accepted,
              :initial_status_not_draft,
              :name_invalid,
              :version_empty,
              :graph_structure_invalid
            ],
       do: Response.unprocessable(conn, "validation failed")

  defp render_install(conn, {:error, {:graph_validation_failed, _violations}}),
    do: Response.unprocessable(conn, "validation failed")

  defp render_install(conn, {:error, %Ecto.Changeset{}}),
    do: Response.unprocessable(conn, "validation failed")

  # `common_error()`'s tuple member. It is a NAMED member of `install_error()`,
  # so by section 8.5's completeness rule it may not reach the last-resort
  # clause below, even though both produce the same 500. It needs a clause of
  # its own rather than an entry in the guard above, because that guard's
  # `reason in [...]` list can only hold atoms and this member is a 2-tuple.
  defp render_install(conn, {:error, {:transaction_failed, _exception}}),
    do: Response.internal_error(conn)

  # Clause of last resort, for genuinely unexpected failures only. Every named
  # member of `install_error()` is mapped above; when that type gains a
  # member, this module gains a clause in the same change
  # (docs/anti-patterns.md -- type-table-vs-error-map drift).
  defp render_install(conn, {:error, _unexpected}), do: Response.internal_error(conn)

  defp malformed_variable_schema(conn, key) do
    Response.unprocessable(
      conn,
      "variable schema #{inspect(key)} is not a well-formed JSON Schema document"
    )
  end

  # ── POST /solution-packs/:pack_id/update-review (design §3) ──────────────

  @update_review_schema [
    %FieldConstraint{
      name: "target_version",
      required: true,
      type: :string,
      reject_empty_string: true,
      max_length: 255
    },
    %FieldConstraint{name: "theirs_artefacts", required: true, type: :array, min_items: 0},
    %FieldConstraint{name: "incoming_artefacts", required: true, type: :array, min_items: 0}
  ]

  defp handle_update_review(conn, pack_id) do
    case object_body(conn) do
      :error ->
        Response.bad_request(conn, "invalid body")

      {:ok, body} ->
        case Validation.validate(@update_review_schema, body) do
          {:errors, field_errors} ->
            Response.send_problem(conn, Validation.problem(field_errors))

          {:ok, attrs} ->
            run_update_review(conn, pack_id, attrs)
        end
    end
  end

  defp run_update_review(conn, pack_id, attrs) do
    target_version = Map.fetch!(attrs, "target_version")
    theirs_raw = Map.fetch!(attrs, "theirs_artefacts")
    incoming_raw = Map.fetch!(attrs, "incoming_artefacts")

    case validate_artefact_entries("theirs_artefacts", theirs_raw) ++
           validate_artefact_entries("incoming_artefacts", incoming_raw) do
      [_ | _] = field_errors ->
        Response.send_problem(conn, Validation.problem(field_errors))

      [] ->
        if theirs_raw == [] and incoming_raw == [] do
          Response.unprocessable(
            conn,
            "theirs_artefacts and incoming_artefacts must not both be empty"
          )
        else
          compute_and_render_review(
            conn,
            pack_id,
            target_version,
            Enum.map(theirs_raw, &to_artefact_input/1),
            Enum.map(incoming_raw, &to_artefact_input/1)
          )
        end
    end
  end

  defp compute_and_render_review(conn, pack_id, target_version, theirs, incoming) do
    with {:ok, tenant_id} <- TenantProvisioning.tenant_id_for_schema_name(prefix(conn)),
         {:ok, plan} <-
           Definitions.compute_pack_update_plan(
             tenant_id,
             pack_id,
             target_version,
             theirs,
             incoming
           ) do
      Response.ok(conn, update_review_response_map(pack_id, target_version, plan))
    else
      # Route-level pre-check above makes this unreachable in practice --
      # defensive only, same "type-table-vs-error-map drift" idiom
      # render_install/2's last-resort clause documents (design §3.4).
      {:error, :empty_artefact_set} ->
        Response.internal_error(conn)

      # tenant_id_for_schema_name/1 failure -- a route-construction bug
      # (unscoped request reaching this handler), same treatment
      # render_install/2 gives :missing_prefix/:invalid_schema_name.
      {:error, _reason} ->
        Response.internal_error(conn)
    end
  end

  # ── POST /solution-packs/:pack_id/update-apply (design §4) ───────────────

  @update_apply_schema [
    %FieldConstraint{
      name: "target_version",
      required: true,
      type: :string,
      reject_empty_string: true,
      max_length: 255
    },
    %FieldConstraint{name: "theirs_artefacts", required: true, type: :array, min_items: 0},
    %FieldConstraint{name: "incoming_artefacts", required: true, type: :array, min_items: 0},
    %FieldConstraint{name: "resolutions", required: true, type: :array, min_items: 0}
  ]

  @resolution_values ["keep_local", "take_incoming", "merged"]

  defp handle_update_apply(conn, pack_id) do
    case object_body(conn) do
      :error ->
        Response.bad_request(conn, "invalid body")

      {:ok, body} ->
        case Validation.validate(@update_apply_schema, body) do
          {:errors, field_errors} ->
            Response.send_problem(conn, Validation.problem(field_errors))

          {:ok, attrs} ->
            run_update_apply(conn, pack_id, attrs)
        end
    end
  end

  defp run_update_apply(conn, pack_id, attrs) do
    target_version = Map.fetch!(attrs, "target_version")
    theirs_raw = Map.fetch!(attrs, "theirs_artefacts")
    incoming_raw = Map.fetch!(attrs, "incoming_artefacts")
    resolutions_raw = Map.fetch!(attrs, "resolutions")

    field_errors =
      validate_artefact_entries("theirs_artefacts", theirs_raw) ++
        validate_artefact_entries("incoming_artefacts", incoming_raw) ++
        validate_resolution_entries(resolutions_raw)

    case field_errors do
      [_ | _] ->
        Response.send_problem(conn, Validation.problem(field_errors))

      [] ->
        if theirs_raw == [] and incoming_raw == [] do
          Response.unprocessable(
            conn,
            "theirs_artefacts and incoming_artefacts must not both be empty"
          )
        else
          apply_with_actor(
            conn,
            pack_id,
            target_version,
            Enum.map(theirs_raw, &to_artefact_input/1),
            Enum.map(incoming_raw, &to_artefact_input/1),
            Enum.map(resolutions_raw, &to_resolution_input/1)
          )
        end
    end
  end

  # `opts[:actor_id]` (`pack_update_resolutions.resolved_by`) is read from
  # this same actor_id/1 helper this router already has, not a
  # caller-supplied body field (design §6, "resolved_by attribution"). A nil
  # actor is a route-construction bug (auth pipeline not run), same
  # treatment install_document/1 already gives that case.
  defp apply_with_actor(conn, pack_id, target_version, theirs, incoming, resolutions) do
    case actor_id(conn) do
      actor_id when is_binary(actor_id) ->
        opts = Keyword.put(conn.assigns.scoped_opts, :actor_id, actor_id)

        render_update_apply(
          conn,
          SolutionPack.apply_pack_update(
            pack_id,
            target_version,
            theirs,
            incoming,
            resolutions,
            opts
          )
        )

      nil ->
        Response.internal_error(conn)
    end
  end

  defp render_update_apply(conn, {:ok, result}), do: Response.ok(conn, apply_result_map(result))

  defp render_update_apply(conn, {:error, {:unresolved_conflict, artefact_type, artefact_id}}) do
    # Caller-supplied values, safe to echo -- same reasoning render_install/2's
    # `key` echo convention uses for caller-submitted identifiers (design §4.5).
    Response.conflict(
      conn,
      "unresolved conflict on artefact_type=#{artefact_type} artefact_id=#{artefact_id}"
    )
  end

  # Route-level pre-check above makes this unreachable in practice --
  # defensive only, same as compute_and_render_review/5's own clause.
  defp render_update_apply(conn, {:error, :empty_artefact_set}),
    do: Response.internal_error(conn)

  # Clause of last resort -- covers common_error() members and
  # {:invalid_resolution, ...} (not reachable through this router's own
  # validation, design §4.5), same "type-table-vs-error-map drift" idiom
  # render_install/2's trailing catch-all documents.
  defp render_update_apply(conn, {:error, _unexpected}), do: Response.internal_error(conn)

  # ── update-review/update-apply shared helpers ─────────────────────────────

  defp prefix(conn), do: Keyword.get(conn.assigns.scoped_opts, :prefix)

  defp to_artefact_input(%{"artefact_type" => type, "artefact_id" => id, "content" => content}) do
    %{artefact_type: type, artefact_id: id, content: content}
  end

  defp to_resolution_input(
         %{"artefact_type" => type, "artefact_id" => id, "resolution" => resolution} = entry
       ) do
    %{
      artefact_type: type,
      artefact_id: id,
      resolution: resolution_atom(resolution),
      resolved_content: Map.get(entry, "resolved_content")
    }
  end

  defp resolution_atom("keep_local"), do: :keep_local
  defp resolution_atom("take_incoming"), do: :take_incoming
  defp resolution_atom("merged"), do: :merged

  # No per-element-shape rule exists in the FieldConstraint vocabulary
  # (design §3.2), so each artefact entry is validated here, after
  # Validation.validate/2 has already established the enclosing field is a
  # (possibly empty) array -- same "post-check after array-type validation"
  # idiom export_with_ids/3's own Enum.all?/2 check already works around.
  defp validate_artefact_entries(field_name, list) do
    list
    |> Enum.with_index()
    |> Enum.reduce([], fn {entry, index}, acc ->
      case validate_artefact_entry(entry) do
        :ok -> acc
        {:error, reason} -> [artefact_field_error(field_name, index, reason) | acc]
      end
    end)
    |> Enum.reverse()
  end

  defp validate_artefact_entry(entry) when is_map(entry) do
    with {:ok, _type} <- fetch_bounded_string(entry, "artefact_type"),
         {:ok, _id} <- fetch_bounded_string(entry, "artefact_id"),
         {:ok, _content} <- fetch_string(entry, "content") do
      :ok
    end
  end

  defp validate_artefact_entry(_not_an_object), do: {:error, :not_an_object}

  defp artefact_field_error(field_name, index, reason) do
    %FieldError{
      field: "#{field_name}[#{index}]",
      constraint: "artefact_shape",
      message: artefact_shape_message(reason)
    }
  end

  defp artefact_shape_message(:not_an_object), do: "artefact entry must be a JSON object"
  defp artefact_shape_message({:blank, key}), do: "#{key} must not be empty"
  defp artefact_shape_message({:too_long, key}), do: "#{key} must not exceed 255 bytes"

  defp artefact_shape_message({:missing_or_wrong_type, key}),
    do: "#{key} is required and must be a string"

  # Each `resolutions[]` entry validated here (design §4.2): `artefact_type`/
  # `artefact_id` share the same non-empty/≤255-byte rule as artefact
  # entries above; `resolution` must be exactly one of the three
  # `PackUpdateResolution.resolution()` wire strings; `resolved_content` is
  # required (non-empty string) iff `resolution == "merged"`, and must be
  # absent or `null` for the other two.
  defp validate_resolution_entries(list) do
    list
    |> Enum.with_index()
    |> Enum.reduce([], fn {entry, index}, acc ->
      case validate_resolution_entry(entry) do
        :ok -> acc
        {:error, reason} -> [resolution_field_error(index, reason) | acc]
      end
    end)
    |> Enum.reverse()
  end

  defp validate_resolution_entry(entry) when is_map(entry) do
    with {:ok, _type} <- fetch_bounded_string(entry, "artefact_type"),
         {:ok, _id} <- fetch_bounded_string(entry, "artefact_id"),
         {:ok, resolution} <- fetch_resolution_value(entry),
         :ok <- check_resolved_content(entry, resolution) do
      :ok
    end
  end

  defp validate_resolution_entry(_not_an_object), do: {:error, :not_an_object}

  defp fetch_resolution_value(entry) do
    case Map.get(entry, "resolution") do
      value when value in @resolution_values -> {:ok, value}
      _other -> {:error, :invalid_resolution_value}
    end
  end

  defp check_resolved_content(entry, "merged") do
    case Map.get(entry, "resolved_content") do
      value when is_binary(value) and value != "" -> :ok
      _other -> {:error, :missing_resolved_content}
    end
  end

  defp check_resolved_content(entry, _keep_local_or_take_incoming) do
    case Map.get(entry, "resolved_content") do
      nil -> :ok
      _present -> {:error, :unexpected_resolved_content}
    end
  end

  defp resolution_field_error(index, reason) do
    %FieldError{
      field: "resolutions[#{index}]",
      constraint: "resolution_shape",
      message: resolution_shape_message(reason)
    }
  end

  defp resolution_shape_message(:not_an_object), do: "resolution entry must be a JSON object"
  defp resolution_shape_message({:blank, key}), do: "#{key} must not be empty"
  defp resolution_shape_message({:too_long, key}), do: "#{key} must not exceed 255 bytes"

  defp resolution_shape_message({:missing_or_wrong_type, key}),
    do: "#{key} is required and must be a string"

  defp resolution_shape_message(:invalid_resolution_value),
    do: "resolution must be one of \"keep_local\", \"take_incoming\", \"merged\""

  defp resolution_shape_message(:missing_resolved_content),
    do:
      "resolved_content is required and must be a non-empty string when resolution is \"merged\""

  defp resolution_shape_message(:unexpected_resolved_content),
    do: "resolved_content must be absent or null unless resolution is \"merged\""

  defp fetch_bounded_string(map, key) do
    case Map.get(map, key) do
      value when is_binary(value) and byte_size(value) == 0 -> {:error, {:blank, key}}
      value when is_binary(value) and byte_size(value) > 255 -> {:error, {:too_long, key}}
      value when is_binary(value) -> {:ok, value}
      _other -> {:error, {:missing_or_wrong_type, key}}
    end
  end

  defp fetch_string(map, key) do
    case Map.get(map, key) do
      value when is_binary(value) -> {:ok, value}
      _other -> {:error, {:missing_or_wrong_type, key}}
    end
  end

  # ── Response allowlists (INV-2) — update-review/update-apply ─────────────

  # Wire-name mapping (design §3.3): classify_artefact/3's internal atoms vs
  # EO-001's own four-way vocabulary. Deliberate translation, not accidental
  # drift.
  defp classification_wire(:unchanged), do: "unchanged"
  defp classification_wire(:clean_update), do: "safe_to_update"
  defp classification_wire(:local_only), do: "local_only"
  defp classification_wire(:conflict), do: "both_sides_conflict"

  defp action_wire(:advanced_to_incoming), do: "advanced_to_incoming"
  defp action_wire(:advanced_to_merged), do: "advanced_to_merged"
  defp action_wire(:left_unchanged), do: "left_unchanged"

  # Hand-built, explicit key list (INV-2) -- never a bare pass-through of
  # compute_pack_update_plan/5's own plan() map. base/theirs/incoming content
  # strings are deliberately NOT echoed (design §6, "Response never echoes
  # raw content").
  defp update_review_response_map(pack_id, target_version, plan) do
    %{
      "pack_id" => pack_id,
      "target_version" => target_version,
      "entries" => Enum.map(plan.entries, &plan_entry_map/1),
      "has_unresolved_conflicts" => plan.has_unresolved_conflicts
    }
  end

  defp plan_entry_map(entry) do
    %{
      "artefact_type" => entry.artefact_type,
      "artefact_id" => entry.artefact_id,
      "classification" => classification_wire(entry.classification),
      "resolved" => entry.resolved
    }
  end

  # Hand-built, explicit key list (INV-2) -- never a bare pass-through of
  # apply_pack_update/6's own apply_result() map. resolved_content/incoming
  # content strings are deliberately NOT echoed (design §6).
  defp apply_result_map(result) do
    %{
      "pack_id" => result.pack_id,
      "target_version" => result.target_version,
      "applied_entries" => Enum.map(result.applied_entries, &applied_entry_wire_map/1),
      "resolutions_recorded" => result.resolutions_recorded
    }
  end

  defp applied_entry_wire_map(entry) do
    %{
      "artefact_type" => entry.artefact_type,
      "artefact_id" => entry.artefact_id,
      "classification" => classification_wire(entry.classification),
      "action" => action_wire(entry.action)
    }
  end

  # ── Shared helpers ────────────────────────────────────────────────────────

  defp object_body(conn) do
    case conn.body_params do
      %{"_json" => _non_object} -> :error
      body when is_map(body) -> {:ok, body}
      _other -> :error
    end
  end

  defp actor_id(conn) do
    case conn.assigns[:auth_context] do
      %{user_id: user_id} when is_binary(user_id) -> user_id
      _other -> nil
    end
  end

  # ── Response allowlists (INV-2) ───────────────────────────────────────────

  # Hand-built, explicit key list -- never a Jason.Encoder derivation over an
  # Ecto struct, and never a bare pass-through of the context module's map.
  @spec pack_document_map(SolutionPack.pack_document()) :: map()
  defp pack_document_map(document) do
    %{
      "pack_id" => document.pack_id,
      "version" => document.version,
      "bpm_export_schema_version" => document.bpm_export_schema_version,
      "exported_at" => document.exported_at,
      "definitions" => Enum.map(document.definitions, &packed_definition_map/1),
      "service_catalog_entries" => document.service_catalog_entries,
      "variable_schemas" => Enum.map(document.variable_schemas, &packed_variable_schema_map/1),
      "manifest" => %{"required_roles" => document.manifest.required_roles}
    }
  end

  @spec packed_definition_map(SolutionPack.packed_definition()) :: map()
  defp packed_definition_map(packed) do
    %{
      "definition_id" => packed.definition_id,
      "process_key" => packed.process_key,
      "name" => packed.name,
      "version" => packed.version,
      "graph" => packed.graph
    }
  end

  @spec packed_variable_schema_map(SolutionPack.packed_variable_schema()) :: map()
  defp packed_variable_schema_map(packed) do
    %{
      "definition_id" => packed.definition_id,
      "schema_name" => packed.schema_name,
      "schema_content" => packed.schema_content
    }
  end

  @spec install_result_map(SolutionPack.install_result()) :: map()
  defp install_result_map(result) do
    %{
      "pack_id" => result.pack_id,
      "version" => result.version,
      "install_id" => result.install_id,
      "installed_definitions" =>
        Enum.map(result.installed_definitions, &installed_definition_map/1),
      "variable_schemas_written" => result.variable_schemas_written,
      "role_mapping_checklist" =>
        Enum.map(result.role_mapping_checklist, fn entry ->
          %{"role_name" => entry.role_name, "bound" => entry.bound}
        end),
      "warnings" => result.warnings
    }
  end

  @spec installed_definition_map(SolutionPack.installed_definition()) :: map()
  defp installed_definition_map(installed) do
    %{
      "source_definition_id" => installed.source_definition_id,
      "new_definition_id" => installed.new_definition_id,
      "process_key" => installed.process_key,
      "status" => installed.status
    }
  end
end
