defmodule Letflow.Routers.SolutionPacks do
  @moduledoc """
  Solution-pack export/install sub-router (REQ-078, design
  `lib/letflow/design/req078-supporting-routes.md` §8). Ports
  `src/api/routes/solution_packs.zig`'s `handleExport` (L29) and
  `handleInstall` (L110). Mounted at `/solution-packs` by
  `Letflow.Plugs.ApiPipeline`, so the full paths under `/api/v1` are
  `/api/v1/solution-packs/export` and `/api/v1/solution-packs/install`.

  | Handler | Method/path                     | Delegate                                     | Auth | Response                    |
  |---------|---------------------------------|----------------------------------------------|------|-----------------------------|
  | export  | `POST /solution-packs/export`   | `Letflow.Definitions.SolutionPack.export/3`  | none in this requirement (REQ-131) | 200, the pack document |
  | install | `POST /solution-packs/install`  | `Letflow.Definitions.SolutionPack.install/3` | none in this requirement (REQ-131) | 200, the install result |

  ## The R-Co path's `{tenant_id}` segment is DROPPED (INV-1)

  R-Co serves these at
  `POST /api/v1/tenants/{tenant_id}/solution-packs/export` and `.../install` —
  the tenant is **caller-supplied in the path**. Letflow drops that segment
  entirely.

  > **The tenant a solution-pack request reads from and writes into is derived
  > solely from `Letflow.Api.Context.scoped_repo_opts/1`, i.e. solely from
  > `conn.assigns[:auth_context][:tenant_id]`. No tenant identifier appears
  > anywhere in these two URLs, so no caller-supplied tenant value can reach a
  > `:prefix` — not by precedence, not by fallback, not by a future
  > refactor.**

  Keeping the segment "for path fidelity" and 404-ing on a mismatch was
  considered and rejected: a path segment that is authoritative for nothing is
  a standing invitation for a later reader to "wire it up", which would be a
  cross-tenant write. It was rejected a second time because `/tenants` is
  already forwarded to `Letflow.Routers.Tenants`, so that shape would put pack
  export/install inside the PLATFORM_ADMIN-only tenant-administration router —
  the wrong permission neighbourhood.

  ## INV-1, both directions

  **Export** reads only through `opts[:prefix]`. A `definition_id` owned by
  another tenant is invisible in the caller's schema and can only produce a
  422 whose detail deliberately **does not echo the id** — echoing it would
  confirm to a prober that the id exists somewhere (INV-5).

  **Install** writes every definition and every `variable_schemas` row with
  that same prefix. The single exception is the one `solution_pack_installs`
  row, whose table is global by REQ-041's design; its `tenant_id` is *derived*
  from the resolved prefix via
  `Letflow.TenantProvisioning.tenant_id_for_schema_name/1` inside the context
  module, never accepted as a caller-supplied field.

  ## The `variable_schemas` write path (AC8)

  Install writes `variable_schemas` rows **only** through
  `Letflow.Definitions.register_variable_schemas/3` — the single shared
  registration function REQ-082's definition import also calls. **No second
  insert path into that table exists in the route layer, or anywhere else in
  `lib/`.** This module performs no `Repo` call of any kind; naming the table
  and the function here is a pointer to the single path, not a second one.

  ## Deliberate non-ports, each with its reason and owner

    * **`service_catalog_entries` / `409 CATALOG_CONFLICT`**
      (`solution_packs.zig:135`) — Letflow has no service catalog;
      `services.zig` owns stage **S6**. Export emits `[]`; install rejects a
      non-empty array with **422** rather than silently discarding
      tenant-supplied content.
    * **`MODULE_NON_EXPORTABLE`** (`solution_packs.zig:83`) — no
      process-module packaging in Letflow; `process_modules.zig` owns stage
      **S5**.
    * **`409 TenantInactive`** (`solution_packs.zig:127-134`) — already
      enforced **upstream**: `Letflow.Plugs.TenantStatus` runs in
      `Letflow.Plugs.ApiPipeline` before any sub-router and rejects an
      inactive tenant with `403 tenant_inactive` for every method. A 409
      branch here could never fire.
    * **`409 VARIABLE_SCHEMA_CONFLICT`** (`solution_packs.zig:136`) —
      **unreachable in Letflow**, not merely unported. Install creates every
      definition it writes schemas for, and `ProcessDefinition`'s primary key
      is autogenerated, so every `(definition_id, variable_key)` pair it
      writes has a brand-new id half. The proof is in
      `Letflow.Definitions.SolutionPack`'s moduledoc, **together with the
      standing condition that invalidates it**: if a later requirement adds an
      install mode that attaches variable schemas to a *pre-existing*
      definition, the conflict becomes reachable and must be reinstated.
    * **R-Co's idempotent re-install** (`buildIdempotentResult`,
      `src/solution/store.zig:682`, called from `:337`) — R-Co returns a
      synthetic success for an already-installed pack. **Letflow returns 409**,
      from `uq_solution_pack_install_active` and/or from
      `{:error, :duplicate_name_version}`, and aborts the whole install. If
      idempotent re-install is wanted it needs its own requirement.
    * **503 `PoolExhausted`** — Ecto/DBConnection surfaces pool exhaustion as
      a raised `DBConnection.ConnectionError`, not an `{:error, :pool_exhausted}`
      tuple, so there is no tuple to match and a 503 clause would be a branch
      nothing can reach.

  ## Authorization gap — REQ-131 closes it

  Neither route calls `Letflow.Api.Authorization.evaluate_access/2`.
  `endpoint_policy_key/2` has **no clause** for `POST /solution-packs/*` —
  there is no existing policy clause to extend (R-Co's `authorization.zig`
  has no entry for these paths either), and deciding what
  permission a pack install requires is a policy question that belongs to
  **REQ-130/REQ-131**, not to a
  route-port requirement. Inventing a route-local permission check here was
  explicitly ruled out (REQ-069's whole point is one matrix).

  These endpoints are therefore **authenticated** (via
  `Letflow.Plugs.AuthPipeline`) and **tenant-scoped** (via
  `scoped_repo_opts/1`), but **not permission-gated**. **REQ-131 is the
  closer.** This gap is stated here so it is visible rather than silent.

  ## Ordering guarantee

  Honours the contract stated in `Letflow.Routers.Tenants`'s moduledoc section
  **"Ordering guarantee (design §6.1)"**: no `Repo` call of any kind —
  including a pre-fetch read — happens before the preamble has resolved the
  scoped prefix. Here that is structural rather than merely observed: **this
  module performs no `Repo` call at all**; every read and write is inside
  `Letflow.Definitions.SolutionPack`, which cannot be reached without the
  prefix, because the prefix is the `opts` argument.

  ## `sandbox_access.zig` is NOT ported by REQ-078

  Recorded here as the nearest module in the requirement.
  `src/api/routes/sandbox_access.zig` (181 lines) is deliberately excluded,
  for three independent reasons any one of which suffices: it exports no
  `handle*` entry point (its three public functions are guards a route calls,
  not a route); its only consumer is `routes/agent_sandboxes.zig`, the
  runtime-agent subsystem owning stage **post-S6**, so porting it in S4 would
  ship a guard with no S4 caller to guard (the REQ-056 partial-backing-subsystem
  failure mode); and `checkProbeRate` is rate limiting, which needs the
  per-tenant counter storage REQ-068's SCOPE BOUNDARY paragraph explicitly
  defers. It moves with `agent_sandboxes.zig` to post-S6 — see the group-(b)
  table in `docs/migration/stage-4-api-surface.md`.
  """

  use Letflow.Api.AuthorizedRouter

  alias Letflow.Api.Response
  alias Letflow.Api.Validation
  alias Letflow.Api.Validation.FieldConstraint
  alias Letflow.Definitions.SolutionPack

  # REQ-131: endpoint_policy_key/2 has no clause for either route (see
  # "Authorization gap" below) -- :DefinitionsRead/:DefinitionsCreate are
  # route-declared policy keys (both real endpoint_policy_key() values,
  # each already backed by a required_permission/1 clause -- :DefinitionsRead
  # and :DefinitionsWrite respectively), reusing the closest-matching
  # existing policy keys (export reads existing definitions, same
  # permission class as GET /definitions*; install creates new definitions
  # and their variable_schemas rows, same permission class as
  # POST /definitions), not derived from Authorization.endpoint_policy_key/2.
  # Both named on the enforcement test's explicit allowlist (design §4) --
  # flagged for REVIEWER as a judgment call, not silently decided.
  authz_post "/export", :DefinitionsRead do
    handle_export(conn)
  end

  authz_post "/install", :DefinitionsCreate do
    handle_install(conn)
  end

  match _ do
    Response.not_found(conn)
  end

  # ── POST /solution-packs/export (design §8.5) ─────────────────────────────

  @export_schema [
    %FieldConstraint{
      name: "definition_ids",
      required: true,
      type: :array,
      min_items: 1
    },
    %FieldConstraint{
      name: "version",
      required: false,
      type: :string,
      reject_empty_string: true,
      max_length: 64
    }
  ]

  defp handle_export(conn) do
    case object_body(conn) do
      :error ->
        Response.bad_request(conn, "invalid body")

      {:ok, body} ->
        case Validation.validate(@export_schema, body) do
          {:errors, field_errors} ->
            Response.send_problem(conn, Validation.problem(field_errors))

          {:ok, attrs} ->
            export_with_ids(conn, Map.get(attrs, "definition_ids"), Map.get(attrs, "version"))
        end
    end
  end

  # The FieldConstraint vocabulary has no per-element type rule, so the
  # "every id is a string" check (R-Co's `definition_id_must_be_string`) is
  # made here, after validate/2 has established that the field is a non-empty
  # array.
  defp export_with_ids(conn, definition_ids, version) do
    if Enum.all?(definition_ids, &is_binary/1) do
      case SolutionPack.export(definition_ids, version, conn.assigns.scoped_opts) do
        {:ok, document} ->
          Response.ok(conn, pack_document_map(document))

        {:error, {:definition_not_found, _id}} ->
          # INV-5: the detail must NOT echo the id -- doing so would confirm
          # to a prober that some id exists in some other tenant's schema.
          Response.unprocessable(conn, "definition not found")

        {:error, :empty_definition_ids} ->
          Response.unprocessable(conn, "definition_ids must not be empty")

        {:error, _common_error} ->
          Response.internal_error(conn)
      end
    else
      Response.unprocessable(conn, "definition_id must be a string")
    end
  end

  # ── POST /solution-packs/install (design §8.5) ────────────────────────────

  defp handle_install(conn) do
    case conn.body_params do
      empty when empty == %{} ->
        Response.bad_request(conn, "empty body")

      %{"_json" => _non_object} ->
        Response.unprocessable(conn, "invalid pack document")

      document when is_map(document) ->
        install_document(conn, document)

      _other ->
        Response.unprocessable(conn, "invalid pack document")
    end
  end

  defp install_document(conn, document) do
    case actor_id(conn) do
      actor_id when is_binary(actor_id) ->
        render_install(conn, SolutionPack.install(document, actor_id, conn.assigns.scoped_opts))

      # No user id on the auth context -- not a caller error, it means this
      # route was reached without `Letflow.Plugs.AuthPipeline` having done
      # its job. Never falls through to an unscoped write.
      nil ->
        Response.internal_error(conn)
    end
  end

  defp render_install(conn, {:ok, result}), do: Response.ok(conn, install_result_map(result))

  defp render_install(conn, {:error, :invalid_pack_document}),
    do: Response.unprocessable(conn, "invalid pack document")

  defp render_install(conn, {:error, {:unknown_schema_version, _actual}}),
    do: Response.unprocessable(conn, "invalid pack document")

  defp render_install(conn, {:error, :unsupported_pack_section}),
    do: Response.unprocessable(conn, "pack contains an unsupported section")

  # `key` is the caller's own submitted value, so echoing it is safe and
  # useful; `reason`/`path` are internal and are not echoed.
  defp render_install(conn, {:error, {:malformed_variable_schema, key, _reason}}),
    do: malformed_variable_schema(conn, key)

  defp render_install(conn, {:error, {:not_well_formed, key, _path}}),
    do: malformed_variable_schema(conn, key)

  defp render_install(conn, {:error, {:schema_too_deep, key}}),
    do:
      Response.unprocessable(
        conn,
        "variable schema #{inspect(key)} nesting exceeds the maximum depth"
      )

  defp render_install(conn, {:error, {:duplicate_variable_key, key}}),
    do: Response.unprocessable(conn, "duplicate variable_key #{inspect(key)} in pack document")

  # The index is deliberately NOT echoed -- it names a position in a document
  # the caller already holds, and a constant detail keeps the body stable.
  defp render_install(conn, {:error, {:blank_variable_key, _index}}),
    do: Response.unprocessable(conn, "variable_key must not be blank")

  # Same echo convention as `:blank_variable_key` above, and for the same two
  # reasons: the payload is an index into the caller's own document, and the
  # offending key itself is unfit to echo -- it is by definition longer than
  # the 255-byte column, so echoing it would put an unbounded caller-controlled
  # blob into the response body. The limit is named instead.
  defp render_install(conn, {:error, {:variable_key_too_long, _index}}),
    do: Response.unprocessable(conn, "variable_key must not exceed 255 bytes")

  defp render_install(conn, {:error, :duplicate_pack_install}),
    do: Response.conflict(conn, "pack already installed")

  defp render_install(conn, {:error, :duplicate_name_version}),
    do: Response.conflict(conn, "definition already exists")

  # Route-construction bugs, not caller errors -- same treatment as
  # `Letflow.Routers.Instances`'s `:missing_actor_id`.
  defp render_install(conn, {:error, reason})
       when reason in [:missing_prefix, :invalid_definition_id, :invalid_schema_name],
       do: Response.internal_error(conn)

  defp render_install(conn, {:error, reason})
       when reason in [
              :tenant_id_not_accepted,
              :initial_status_not_draft,
              :name_invalid,
              :version_empty,
              :graph_structure_invalid
            ],
       do: Response.unprocessable(conn, "validation failed")

  defp render_install(conn, {:error, {:graph_validation_failed, _violations}}),
    do: Response.unprocessable(conn, "validation failed")

  defp render_install(conn, {:error, %Ecto.Changeset{}}),
    do: Response.unprocessable(conn, "validation failed")

  # `common_error()`'s tuple member. It is a NAMED member of `install_error()`,
  # so by section 8.5's completeness rule it may not reach the last-resort
  # clause below, even though both produce the same 500. It needs a clause of
  # its own rather than an entry in the guard above, because that guard's
  # `reason in [...]` list can only hold atoms and this member is a 2-tuple.
  defp render_install(conn, {:error, {:transaction_failed, _exception}}),
    do: Response.internal_error(conn)

  # Clause of last resort, for genuinely unexpected failures only. Every named
  # member of `install_error()` is mapped above; when that type gains a
  # member, this module gains a clause in the same change
  # (docs/anti-patterns.md -- type-table-vs-error-map drift).
  defp render_install(conn, {:error, _unexpected}), do: Response.internal_error(conn)

  defp malformed_variable_schema(conn, key) do
    Response.unprocessable(
      conn,
      "variable schema #{inspect(key)} is not a well-formed JSON Schema document"
    )
  end

  # ── Shared helpers ────────────────────────────────────────────────────────

  defp object_body(conn) do
    case conn.body_params do
      %{"_json" => _non_object} -> :error
      body when is_map(body) -> {:ok, body}
      _other -> :error
    end
  end

  defp actor_id(conn) do
    case conn.assigns[:auth_context] do
      %{user_id: user_id} when is_binary(user_id) -> user_id
      _other -> nil
    end
  end

  # ── Response allowlists (INV-2) ───────────────────────────────────────────

  # Hand-built, explicit key list -- never a Jason.Encoder derivation over an
  # Ecto struct, and never a bare pass-through of the context module's map.
  @spec pack_document_map(SolutionPack.pack_document()) :: map()
  defp pack_document_map(document) do
    %{
      "pack_id" => document.pack_id,
      "version" => document.version,
      "bpm_export_schema_version" => document.bpm_export_schema_version,
      "exported_at" => document.exported_at,
      "definitions" => Enum.map(document.definitions, &packed_definition_map/1),
      "service_catalog_entries" => document.service_catalog_entries,
      "variable_schemas" => Enum.map(document.variable_schemas, &packed_variable_schema_map/1),
      "manifest" => %{"required_roles" => document.manifest.required_roles}
    }
  end

  @spec packed_definition_map(SolutionPack.packed_definition()) :: map()
  defp packed_definition_map(packed) do
    %{
      "definition_id" => packed.definition_id,
      "process_key" => packed.process_key,
      "name" => packed.name,
      "version" => packed.version,
      "graph" => packed.graph
    }
  end

  @spec packed_variable_schema_map(SolutionPack.packed_variable_schema()) :: map()
  defp packed_variable_schema_map(packed) do
    %{
      "definition_id" => packed.definition_id,
      "schema_name" => packed.schema_name,
      "schema_content" => packed.schema_content
    }
  end

  @spec install_result_map(SolutionPack.install_result()) :: map()
  defp install_result_map(result) do
    %{
      "pack_id" => result.pack_id,
      "version" => result.version,
      "install_id" => result.install_id,
      "installed_definitions" =>
        Enum.map(result.installed_definitions, &installed_definition_map/1),
      "variable_schemas_written" => result.variable_schemas_written,
      "role_mapping_checklist" =>
        Enum.map(result.role_mapping_checklist, fn entry ->
          %{"role_name" => entry.role_name, "bound" => entry.bound}
        end),
      "warnings" => result.warnings
    }
  end

  @spec installed_definition_map(SolutionPack.installed_definition()) :: map()
  defp installed_definition_map(installed) do
    %{
      "source_definition_id" => installed.source_definition_id,
      "new_definition_id" => installed.new_definition_id,
      "process_key" => installed.process_key,
      "status" => installed.status
    }
  end
end
