/* @generated by tools/codegen_list_page.py — boilerplate is auto-generated.
   Edit only inside CUSTOM blocks. Re-run codegen to refresh. */
import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Navigate, useNavigate, Link } from 'react-router-dom'
import { useAuth } from '@/auth/AuthContext'
import { tenantsApi } from '@/api/tenants'
import { queryKeys } from '@/api/queryKeys'
import type { ApiError } from '@/types/api'
import { QueryStateBoundary } from '@/components/ui/QueryStateBoundary'
import { classifyError, type RendererState } from '@/utils/classifyError'

/**
 * TenantsPage
 * PLATFORM_ADMIN-only paginated list of all registered tenants. Displays slug,
 * display name, IDP realm, status, and creation date. Provides per-row Edit
 * navigation (TM-03) and a navigation button to the existing onboarding route
 * (TM-02). Non-PLATFORM_ADMIN users must be redirected to /instances on page
 * load — enforce in the role-gate CUSTOM block.
 */

const PAGE_SIZE = 20

export default function TenantsPage() {
  const { session } = useAuth()
  const navigate = useNavigate()
  const qc = useQueryClient()

  const [search, setSearch] = useState<string>('')
  const [offset, setOffset] = useState<number>(0)
  const [actionError, setActionError] = useState<string | null>(null)
  const [confirmState, setConfirmState] = useState<{ slug: string; action: 'deactivate' | 'reactivate' } | null>(null)

  const listParams = { search: search || undefined, limit: PAGE_SIZE, offset }

  const listQuery = useQuery({
    queryKey: queryKeys.admin.tenants(listParams),
    queryFn: () => tenantsApi.list(listParams),
  })

  const lifecycleMutation = useMutation({
    mutationFn: (payload: { slug: string; action: 'deactivate' | 'reactivate' }) =>
      payload.action === 'deactivate'
        ? tenantsApi.deactivate(payload.slug)
        : tenantsApi.reactivate(payload.slug),
    onSuccess: () => {
      setActionError(null)
      setConfirmState(null)
      qc.invalidateQueries({ queryKey: queryKeys.admin.tenants() })
    },
    onError: (error: unknown) => {
      setActionError(mapLifecycleError(error))
    },
  })

  // CUSTOM: role-gate
  if (!session?.roles.includes('PLATFORM_ADMIN')) {
    return <Navigate to="/instances" replace />
  }

  const data = listQuery.data
  const total = data?.total ?? 0
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE))
  const currentPage = Math.floor(offset / PAGE_SIZE) + 1
  const rendererState: RendererState = listQuery.isLoading ? 'loading' : listQuery.isError ? classifyError(listQuery.error) : 'success'

  function handleSearchChange(value: string) {
    setSearch(value)
    setOffset(0)
  }

  function handleLifecycleAction(slug: string, action: 'deactivate' | 'reactivate') {
    setActionError(null)
    setConfirmState({ slug, action })
  }

  function confirmLifecycleAction() {
    if (!confirmState) {
      return
    }
    lifecycleMutation.mutate(confirmState)
  }

  return (
    <div data-testid="tenants-page" style={{ padding: '1.5rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <h1 style={{ margin: 0 }}>Tenants</h1>
        {/* CUSTOM: add-tenant-link */}
        <Link
          to="/admin/onboarding/new"
          data-testid="register-new-tenant-btn"
          style={{
            display: 'inline-block',
            padding: '.45rem 1rem',
            background: '#2563eb',
            color: '#fff',
            border: 'none',
            borderRadius: '4px',
            textDecoration: 'none',
            fontSize: '.9rem',
            fontWeight: 600,
          }}
        >
          + Add Tenant
        </Link>
      </div>

      <form
        style={{ marginBottom: '1rem' }}
        onSubmit={(e) => e.preventDefault()}
      >
        <input
          data-testid="tenants-search"
          type="text"
          placeholder="slug or display name"
          value={search}
          onChange={(e) => handleSearchChange(e.target.value)}
          style={{
            padding: '.45rem .7rem',
            border: '1px solid #cbd5e1',
            borderRadius: '4px',
            fontSize: '.9rem',
            width: '280px',
          }}
        />
      </form>

      <QueryStateBoundary
        state={rendererState}
        onRetry={() => { void listQuery.refetch() }}
        columns={[{ widthPercent: 15 }, { widthPercent: 30 }, { widthPercent: 15 }, { widthPercent: 10 }, { widthPercent: 15 }, { widthPercent: 15 }]}
      >
      {actionError && (
        <div
          role="alert"
          data-testid="tenant-lifecycle-error"
          style={{
            marginBottom: '1rem',
            padding: '.75rem 1rem',
            borderRadius: '6px',
            border: '1px solid #fca5a5',
            background: '#fff1f2',
            color: '#9f1239',
            fontSize: '.88rem',
          }}
        >
          {actionError}
        </div>
      )}
      {data && (
        <>
          <table
            data-testid="tenants-table"
            style={{ width: '100%', borderCollapse: 'collapse', fontSize: '.9rem' }}
          >
            <thead>
              <tr style={{ background: '#f1f5f9', textAlign: 'left' }}>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>Slug</th>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>Display name</th>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>IDP realm</th>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>Status</th>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>Created</th>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {(data.items ?? []).map((row) => (
                <tr
                  key={row.slug}
                  data-testid={`tenant-row-${row.slug}`}
                  style={row.tenant_type === 'test' ? { background: '#fefce8' } : undefined}
                >
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>{row.slug}</td>
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>
                    {row.tenant_type === 'test' && (
                      <span
                        data-testid={`tenant-type-badge-${row.slug}`}
                        style={{
                          display: 'inline-block',
                          marginRight: '.4rem',
                          padding: '.1rem .4rem',
                          borderRadius: '999px',
                          fontSize: '.72rem',
                          fontWeight: 600,
                          background: '#fef08a',
                          color: '#713f12',
                        }}
                      >
                        TEST
                      </span>
                    )}
                    {row.display_name}{row.tenant_type === 'test' ? ' [TEST]' : ''}
                  </td>
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>{row.idp_realm_id}</td>
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>
                    <span
                      data-testid={`tenant-status-${row.slug}`}
                      style={{
                        display: 'inline-block',
                        padding: '.15rem .5rem',
                        borderRadius: '999px',
                        fontSize: '.78rem',
                        fontWeight: 600,
                        background: row.status === 'ACTIVE' ? '#dcfce7' : '#f1f5f9',
                        color: row.status === 'ACTIVE' ? '#166534' : '#64748b',
                      }}
                    >
                      {row.status === 'ACTIVE' ? 'Active' : 'Inactive'}
                    </span>
                  </td>
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>
                    {new Date(row.created_at).toLocaleDateString()}
                  </td>
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>
                    {/* CUSTOM: row-action-navigate_edit */}
                    <div style={{ display: 'flex', gap: '.4rem', flexWrap: 'wrap' }}>
                      <button
                        type="button"
                        data-testid={`tenant-edit-${row.slug}`}
                        onClick={() => navigate(`/admin/tenants/${row.slug}/edit`)}
                        style={{
                          padding: '.3rem .65rem',
                          border: '1px solid #cbd5e1',
                          borderRadius: '4px',
                          background: '#fff',
                          cursor: 'pointer',
                          fontSize: '.82rem',
                        }}
                      >
                        Edit
                      </button>
                      {row.status === 'ACTIVE' && (
                        <button
                          type="button"
                          data-testid={`tenant-deactivate-${row.slug}`}
                          onClick={() => handleLifecycleAction(row.slug, 'deactivate')}
                          disabled={lifecycleMutation.isPending}
                          style={{
                            padding: '.3rem .65rem',
                            border: '1px solid #dc2626',
                            borderRadius: '4px',
                            background: '#fff',
                            cursor: lifecycleMutation.isPending ? 'not-allowed' : 'pointer',
                            color: '#b91c1c',
                            fontSize: '.82rem',
                            opacity: lifecycleMutation.isPending ? 0.7 : 1,
                          }}
                        >
                          Deactivate
                        </button>
                      )}
                      {row.status === 'INACTIVE' && (
                        <button
                          type="button"
                          data-testid={`tenant-reactivate-${row.slug}`}
                          onClick={() => handleLifecycleAction(row.slug, 'reactivate')}
                          disabled={lifecycleMutation.isPending}
                          style={{
                            padding: '.3rem .65rem',
                            border: '1px solid #15803d',
                            borderRadius: '4px',
                            background: '#fff',
                            cursor: lifecycleMutation.isPending ? 'not-allowed' : 'pointer',
                            color: '#166534',
                            fontSize: '.82rem',
                            opacity: lifecycleMutation.isPending ? 0.7 : 1,
                          }}
                        >
                          Reactivate
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
              {(data.items ?? []).length === 0 && (
                <tr>
                  <td colSpan={6} style={{ padding: '1rem .75rem', color: '#64748b', textAlign: 'center' }}>
                    No tenants found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>

          {total > PAGE_SIZE && (
            <div
              data-testid="tenants-pagination"
              style={{ display: 'flex', gap: '.5rem', alignItems: 'center', marginTop: '1rem' }}
            >
              <button
                type="button"
                disabled={currentPage <= 1}
                onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))}
                style={{
                  padding: '.3rem .65rem',
                  border: '1px solid #cbd5e1',
                  borderRadius: '4px',
                  background: '#fff',
                  cursor: currentPage <= 1 ? 'not-allowed' : 'pointer',
                  opacity: currentPage <= 1 ? 0.5 : 1,
                  fontSize: '.82rem',
                }}
              >
                Previous
              </button>
              <span style={{ fontSize: '.88rem', color: '#64748b' }}>
                Page {currentPage} of {totalPages}
              </span>
              <button
                type="button"
                disabled={currentPage >= totalPages}
                onClick={() => setOffset(offset + PAGE_SIZE)}
                style={{
                  padding: '.3rem .65rem',
                  border: '1px solid #cbd5e1',
                  borderRadius: '4px',
                  background: '#fff',
                  cursor: currentPage >= totalPages ? 'not-allowed' : 'pointer',
                  opacity: currentPage >= totalPages ? 0.5 : 1,
                  fontSize: '.82rem',
                }}
              >
                Next
              </button>
            </div>
          )}
        </>
      )}
      </QueryStateBoundary>

      {confirmState && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="Confirm tenant lifecycle action"
          data-testid="tenant-lifecycle-confirm-dialog"
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(15, 23, 42, .45)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '1rem',
            zIndex: 40,
          }}
        >
          <div
            style={{
              width: 'min(420px, 100%)',
              background: '#fff',
              border: '1px solid #e2e8f0',
              borderRadius: '8px',
              padding: '1rem',
            }}
          >
            <h3 style={{ margin: '0 0 .5rem' }}>
              {confirmState.action === 'deactivate' ? 'Deactivate tenant?' : 'Reactivate tenant?'}
            </h3>
            <p style={{ margin: '0 0 .9rem', color: '#475569', fontSize: '.9rem' }}>
              {confirmState.action === 'deactivate'
                ? `This blocks normal tenant operations for ${confirmState.slug} until it is reactivated.`
                : `This restores normal tenant operations for ${confirmState.slug}.`}
            </p>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '.5rem' }}>
              <button
                type="button"
                data-testid="tenant-lifecycle-cancel"
                onClick={() => setConfirmState(null)}
                style={{
                  padding: '.4rem .8rem',
                  border: '1px solid #cbd5e1',
                  borderRadius: '4px',
                  background: '#fff',
                  cursor: 'pointer',
                }}
              >
                Cancel
              </button>
              <button
                type="button"
                data-testid="tenant-lifecycle-confirm"
                onClick={confirmLifecycleAction}
                disabled={lifecycleMutation.isPending}
                style={{
                  padding: '.4rem .8rem',
                  border: 'none',
                  borderRadius: '4px',
                  background: confirmState.action === 'deactivate' ? '#dc2626' : '#16a34a',
                  color: '#fff',
                  cursor: lifecycleMutation.isPending ? 'not-allowed' : 'pointer',
                  opacity: lifecycleMutation.isPending ? 0.7 : 1,
                }}
              >
                {lifecycleMutation.isPending
                  ? (confirmState.action === 'deactivate' ? 'Deactivating...' : 'Reactivating...')
                  : (confirmState.action === 'deactivate' ? 'Deactivate' : 'Reactivate')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function mapLifecycleError(error: unknown): string {
  const fallback = 'An unexpected error occurred. Please try again.'
  const apiError = error as ApiError | undefined
  const code = String(apiError?.code ?? '').toLowerCase()

  if (code.includes('invalid_tenant_slug')) {
    return 'Tenant identifier is invalid. Use lowercase letters, digits, and hyphens only.'
  }
  if (code.includes('invalid_lifecycle_action')) {
    return 'Unsupported tenant lifecycle action.'
  }
  if (code.includes('invalid_lifecycle_payload')) {
    return 'This action does not accept request fields.'
  }
  if (code.includes('tenant_not_found')) {
    return 'This tenant no longer exists.'
  }
  if (code.includes('tenant_inactive')) {
    return 'This tenant is inactive. Contact a platform administrator.'
  }
  if (code.includes('forbidden')) {
    return 'You are not authorized to manage tenant lifecycle.'
  }

  return fallback
}
