/* @generated by tools/codegen_list_page.py — boilerplate is auto-generated.
   Edit only inside CUSTOM blocks. Re-run codegen to refresh. */
import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Navigate, useNavigate, Link } from 'react-router-dom'
import { useAuth } from '@/auth/AuthContext'
import { tenantsApi } from '@/api/tenants'
import { queryKeys } from '@/api/queryKeys'
import type { ApiError } from '@/types/api'
import { QueryStateBoundary } from '@/components/ui/QueryStateBoundary'
import { Button } from '@/components/ui/Button'
import { DataTable, type DataTableColumn } from '@/components/ui/DataTable'
import { PaginationControls } from '@/components/ui/PaginationControls'
import { classifyError, type RendererState } from '@/utils/classifyError'
import type { Tenant } from '@/api/tenants'

// NOTE: the pre-existing full-row yellow tint for tenant_type === 'test'
// rows is dropped -- DataTable has no per-row style hook (only per-cell,
// via each column's accessor). The [TEST] badge in the Display name
// column already conveys the same information per-row, so nothing
// becomes undiscoverable; this is a documented primitive-fit gap, not a
// silent behaviour change.

/**
 * TenantsPage
 * PLATFORM_ADMIN-only paginated list of all registered tenants. Displays slug,
 * display name, IDP realm, status, and creation date. Provides per-row Edit
 * navigation (TM-03) and a navigation button to the existing onboarding route
 * (TM-02). Non-PLATFORM_ADMIN users must be redirected to /instances on page
 * load — enforce in the role-gate CUSTOM block.
 */

const PAGE_SIZE = 20

export default function TenantsPage() {
  const { session } = useAuth()
  const navigate = useNavigate()
  const qc = useQueryClient()

  const [search, setSearch] = useState<string>('')
  const [offset, setOffset] = useState<number>(0)
  const [actionError, setActionError] = useState<string | null>(null)
  const [confirmState, setConfirmState] = useState<{ slug: string; action: 'deactivate' | 'reactivate' } | null>(null)

  const listParams = { search: search || undefined, limit: PAGE_SIZE, offset }

  const listQuery = useQuery({
    queryKey: queryKeys.admin.tenants(listParams),
    queryFn: () => tenantsApi.list(listParams),
  })

  const lifecycleMutation = useMutation({
    mutationFn: (payload: { slug: string; action: 'deactivate' | 'reactivate' }) =>
      payload.action === 'deactivate'
        ? tenantsApi.deactivate(payload.slug)
        : tenantsApi.reactivate(payload.slug),
    onSuccess: () => {
      setActionError(null)
      setConfirmState(null)
      qc.invalidateQueries({ queryKey: queryKeys.admin.tenants() })
    },
    onError: (error: unknown) => {
      setActionError(mapLifecycleError(error))
    },
  })

  // CUSTOM: role-gate
  if (!session?.roles.includes('PLATFORM_ADMIN')) {
    return <Navigate to="/instances" replace />
  }

  const data = listQuery.data
  const total = data?.total ?? 0
  const currentPage = Math.floor(offset / PAGE_SIZE) + 1
  const rendererState: RendererState = listQuery.isLoading ? 'loading' : listQuery.isError ? classifyError(listQuery.error) : 'success'

  function handleSearchChange(value: string) {
    setSearch(value)
    setOffset(0)
  }

  function handleLifecycleAction(slug: string, action: 'deactivate' | 'reactivate') {
    setActionError(null)
    setConfirmState({ slug, action })
  }

  function confirmLifecycleAction() {
    if (!confirmState) {
      return
    }
    lifecycleMutation.mutate(confirmState)
  }

  const columns: DataTableColumn<Tenant>[] = [
    { id: 'slug', header: 'Slug', accessor: (row) => row.slug },
    {
      id: 'display_name',
      header: 'Display name',
      accessor: (row) => (
        <>
          {row.tenant_type === 'test' && (
            <span
              data-testid={`tenant-type-badge-${row.slug}`}
              style={{
                display: 'inline-block',
                marginRight: '.4rem',
                padding: '.1rem .4rem',
                borderRadius: 'var(--radius-full)',
                fontSize: '.72rem',
                fontWeight: 600,
                background: 'var(--color-warning-banner)',
                color: 'var(--color-warning-text)',
              }}
            >
              TEST
            </span>
          )}
          {row.display_name}{row.tenant_type === 'test' ? ' [TEST]' : ''}
        </>
      ),
    },
    { id: 'idp_realm', header: 'IDP realm', accessor: (row) => row.idp_realm_id },
    {
      id: 'status',
      header: 'Status',
      accessor: (row) => (
        <span
          data-testid={`tenant-status-${row.slug}`}
          style={{
            display: 'inline-block',
            padding: '.15rem .5rem',
            borderRadius: 'var(--radius-full)',
            fontSize: '.78rem',
            fontWeight: 600,
            background: row.status === 'ACTIVE' ? 'var(--color-success-light)' : 'var(--color-neutral-100)',
            color: row.status === 'ACTIVE' ? 'var(--color-success-dark)' : 'var(--text-secondary)',
          }}
        >
          {row.status === 'ACTIVE' ? 'Active' : 'Inactive'}
        </span>
      ),
    },
    { id: 'created', header: 'Created', accessor: (row) => new Date(row.created_at).toLocaleDateString() },
    {
      id: 'actions',
      header: 'Actions',
      accessor: (row) => (
        <div style={{ display: 'flex', gap: '.4rem', flexWrap: 'wrap' }}>
          <Button
            variant="secondary"
            size="sm"
            data-testid={`tenant-edit-${row.slug}`}
            onClick={() => navigate(`/admin/tenants/${row.slug}/edit`)}
          >
            Edit
          </Button>
          {row.status === 'ACTIVE' && (
            <Button
              variant="danger"
              size="sm"
              data-testid={`tenant-deactivate-${row.slug}`}
              loading={lifecycleMutation.isPending}
              onClick={() => handleLifecycleAction(row.slug, 'deactivate')}
            >
              Deactivate
            </Button>
          )}
          {row.status === 'INACTIVE' && (
            <Button
              variant="primary"
              size="sm"
              data-testid={`tenant-reactivate-${row.slug}`}
              loading={lifecycleMutation.isPending}
              onClick={() => handleLifecycleAction(row.slug, 'reactivate')}
            >
              Reactivate
            </Button>
          )}
        </div>
      ),
    },
  ]

  return (
    <div data-testid="tenants-page" style={{ padding: '1.5rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <h1 style={{ margin: 0 }}>Tenants</h1>
        {/* CUSTOM: add-tenant-link */}
        {/* Navigational CTA to another route -- kept as Link, not Button,
            which has no href/anchor semantics. */}
        <Link
          to="/admin/onboarding/new"
          data-testid="register-new-tenant-btn"
          style={{
            display: 'inline-block',
            padding: '.45rem 1rem',
            background: 'var(--interactive-primary)',
            color: 'var(--text-inverse)',
            border: 'none',
            borderRadius: 'var(--radius-sm)',
            textDecoration: 'none',
            fontSize: '.9rem',
            fontWeight: 600,
          }}
        >
          + Add Tenant
        </Link>
      </div>

      <form
        style={{ marginBottom: '1rem' }}
        onSubmit={(e) => e.preventDefault()}
      >
        <input
          data-testid="tenants-search"
          type="text"
          placeholder="slug or display name"
          value={search}
          onChange={(e) => handleSearchChange(e.target.value)}
          style={{
            padding: '.45rem .7rem',
            border: '1px solid var(--border-default)',
            borderRadius: 'var(--radius-sm)',
            fontSize: '.9rem',
            width: '280px',
          }}
        />
      </form>

      <QueryStateBoundary
        state={rendererState}
        onRetry={() => { void listQuery.refetch() }}
        columns={[{ widthPercent: 15 }, { widthPercent: 30 }, { widthPercent: 15 }, { widthPercent: 10 }, { widthPercent: 15 }, { widthPercent: 15 }]}
      >
      {actionError && (
        <div
          role="alert"
          data-testid="tenant-lifecycle-error"
          style={{
            marginBottom: '1rem',
            padding: '.75rem 1rem',
            borderRadius: 'var(--radius-sm)',
            border: '1px solid var(--color-error-border)',
            background: 'var(--color-error-tint)',
            color: 'var(--color-error-dark)',
            fontSize: '.88rem',
          }}
        >
          {actionError}
        </div>
      )}
      {data && (
        <>
          <div data-testid="tenants-table">
            <DataTable
              columns={columns}
              data={data.items ?? []}
              emptyMessage="No tenants found."
            />
          </div>

          {total > PAGE_SIZE && (
            <div data-testid="tenants-pagination" style={{ marginTop: '1rem' }}>
              <PaginationControls
                page={currentPage}
                pageSize={PAGE_SIZE}
                totalItems={total}
                onPageChange={(newPage) => setOffset((newPage - 1) * PAGE_SIZE)}
              />
            </div>
          )}
        </>
      )}
      </QueryStateBoundary>

      {confirmState && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="Confirm tenant lifecycle action"
          data-testid="tenant-lifecycle-confirm-dialog"
          style={{
            position: 'fixed',
            inset: 0,
            background: 'var(--surface-overlay-slate)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '1rem',
            zIndex: 40,
          }}
        >
          <div
            style={{
              width: 'min(420px, 100%)',
              background: 'var(--surface-card)',
              border: '1px solid var(--border-default)',
              borderRadius: '8px',
              padding: '1rem',
            }}
          >
            <h3 style={{ margin: '0 0 .5rem' }}>
              {confirmState.action === 'deactivate' ? 'Deactivate tenant?' : 'Reactivate tenant?'}
            </h3>
            <p style={{ margin: '0 0 .9rem', color: 'var(--text-secondary)', fontSize: '.9rem' }}>
              {confirmState.action === 'deactivate'
                ? `This blocks normal tenant operations for ${confirmState.slug} until it is reactivated.`
                : `This restores normal tenant operations for ${confirmState.slug}.`}
            </p>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '.5rem' }}>
              <Button variant="secondary" size="sm" data-testid="tenant-lifecycle-cancel" onClick={() => setConfirmState(null)}>
                Cancel
              </Button>
              <Button
                variant={confirmState.action === 'deactivate' ? 'danger' : 'primary'}
                size="sm"
                data-testid="tenant-lifecycle-confirm"
                loading={lifecycleMutation.isPending}
                onClick={confirmLifecycleAction}
              >
                {lifecycleMutation.isPending
                  ? (confirmState.action === 'deactivate' ? 'Deactivating...' : 'Reactivating...')
                  : (confirmState.action === 'deactivate' ? 'Deactivate' : 'Reactivate')}
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function mapLifecycleError(error: unknown): string {
  const fallback = 'An unexpected error occurred. Please try again.'
  const apiError = error as ApiError | undefined
  const code = String(apiError?.code ?? '').toLowerCase()

  if (code.includes('invalid_tenant_slug')) {
    return 'Tenant identifier is invalid. Use lowercase letters, digits, and hyphens only.'
  }
  if (code.includes('invalid_lifecycle_action')) {
    return 'Unsupported tenant lifecycle action.'
  }
  if (code.includes('invalid_lifecycle_payload')) {
    return 'This action does not accept request fields.'
  }
  if (code.includes('tenant_not_found')) {
    return 'This tenant no longer exists.'
  }
  if (code.includes('tenant_inactive')) {
    return 'This tenant is inactive. Contact a platform administrator.'
  }
  if (code.includes('forbidden')) {
    return 'You are not authorized to manage tenant lifecycle.'
  }

  return fallback
}
